/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the NtfySettingsOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NtfySettingsOptions{}

// NtfySettingsOptions struct for NtfySettingsOptions
type NtfySettingsOptions struct {
	Url *string `json:"url,omitempty"`
	Topic *string `json:"topic,omitempty"`
	AuthMethodUsernamePassword *bool `json:"authMethodUsernamePassword,omitempty"`
	Username *string `json:"username,omitempty"`
	Password *string `json:"password,omitempty"`
	AuthMethodToken *bool `json:"authMethodToken,omitempty"`
	Token *string `json:"token,omitempty"`
}

// NewNtfySettingsOptions instantiates a new NtfySettingsOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNtfySettingsOptions() *NtfySettingsOptions {
	this := NtfySettingsOptions{}
	return &this
}

// NewNtfySettingsOptionsWithDefaults instantiates a new NtfySettingsOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNtfySettingsOptionsWithDefaults() *NtfySettingsOptions {
	this := NtfySettingsOptions{}
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *NtfySettingsOptions) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfySettingsOptions) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *NtfySettingsOptions) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *NtfySettingsOptions) SetUrl(v string) {
	o.Url = &v
}

// GetTopic returns the Topic field value if set, zero value otherwise.
func (o *NtfySettingsOptions) GetTopic() string {
	if o == nil || IsNil(o.Topic) {
		var ret string
		return ret
	}
	return *o.Topic
}

// GetTopicOk returns a tuple with the Topic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfySettingsOptions) GetTopicOk() (*string, bool) {
	if o == nil || IsNil(o.Topic) {
		return nil, false
	}
	return o.Topic, true
}

// HasTopic returns a boolean if a field has been set.
func (o *NtfySettingsOptions) HasTopic() bool {
	if o != nil && !IsNil(o.Topic) {
		return true
	}

	return false
}

// SetTopic gets a reference to the given string and assigns it to the Topic field.
func (o *NtfySettingsOptions) SetTopic(v string) {
	o.Topic = &v
}

// GetAuthMethodUsernamePassword returns the AuthMethodUsernamePassword field value if set, zero value otherwise.
func (o *NtfySettingsOptions) GetAuthMethodUsernamePassword() bool {
	if o == nil || IsNil(o.AuthMethodUsernamePassword) {
		var ret bool
		return ret
	}
	return *o.AuthMethodUsernamePassword
}

// GetAuthMethodUsernamePasswordOk returns a tuple with the AuthMethodUsernamePassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfySettingsOptions) GetAuthMethodUsernamePasswordOk() (*bool, bool) {
	if o == nil || IsNil(o.AuthMethodUsernamePassword) {
		return nil, false
	}
	return o.AuthMethodUsernamePassword, true
}

// HasAuthMethodUsernamePassword returns a boolean if a field has been set.
func (o *NtfySettingsOptions) HasAuthMethodUsernamePassword() bool {
	if o != nil && !IsNil(o.AuthMethodUsernamePassword) {
		return true
	}

	return false
}

// SetAuthMethodUsernamePassword gets a reference to the given bool and assigns it to the AuthMethodUsernamePassword field.
func (o *NtfySettingsOptions) SetAuthMethodUsernamePassword(v bool) {
	o.AuthMethodUsernamePassword = &v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *NtfySettingsOptions) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfySettingsOptions) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *NtfySettingsOptions) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *NtfySettingsOptions) SetUsername(v string) {
	o.Username = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *NtfySettingsOptions) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfySettingsOptions) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *NtfySettingsOptions) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *NtfySettingsOptions) SetPassword(v string) {
	o.Password = &v
}

// GetAuthMethodToken returns the AuthMethodToken field value if set, zero value otherwise.
func (o *NtfySettingsOptions) GetAuthMethodToken() bool {
	if o == nil || IsNil(o.AuthMethodToken) {
		var ret bool
		return ret
	}
	return *o.AuthMethodToken
}

// GetAuthMethodTokenOk returns a tuple with the AuthMethodToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfySettingsOptions) GetAuthMethodTokenOk() (*bool, bool) {
	if o == nil || IsNil(o.AuthMethodToken) {
		return nil, false
	}
	return o.AuthMethodToken, true
}

// HasAuthMethodToken returns a boolean if a field has been set.
func (o *NtfySettingsOptions) HasAuthMethodToken() bool {
	if o != nil && !IsNil(o.AuthMethodToken) {
		return true
	}

	return false
}

// SetAuthMethodToken gets a reference to the given bool and assigns it to the AuthMethodToken field.
func (o *NtfySettingsOptions) SetAuthMethodToken(v bool) {
	o.AuthMethodToken = &v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *NtfySettingsOptions) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfySettingsOptions) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *NtfySettingsOptions) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *NtfySettingsOptions) SetToken(v string) {
	o.Token = &v
}

func (o NtfySettingsOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NtfySettingsOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Topic) {
		toSerialize["topic"] = o.Topic
	}
	if !IsNil(o.AuthMethodUsernamePassword) {
		toSerialize["authMethodUsernamePassword"] = o.AuthMethodUsernamePassword
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.AuthMethodToken) {
		toSerialize["authMethodToken"] = o.AuthMethodToken
	}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	return toSerialize, nil
}

type NullableNtfySettingsOptions struct {
	value *NtfySettingsOptions
	isSet bool
}

func (v NullableNtfySettingsOptions) Get() *NtfySettingsOptions {
	return v.value
}

func (v *NullableNtfySettingsOptions) Set(val *NtfySettingsOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableNtfySettingsOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableNtfySettingsOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNtfySettingsOptions(val *NtfySettingsOptions) *NullableNtfySettingsOptions {
	return &NullableNtfySettingsOptions{value: val, isSet: true}
}

func (v NullableNtfySettingsOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNtfySettingsOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


