/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the SettingsJellyfinSyncPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SettingsJellyfinSyncPostRequest{}

// SettingsJellyfinSyncPostRequest struct for SettingsJellyfinSyncPostRequest
type SettingsJellyfinSyncPostRequest struct {
	Cancel *bool `json:"cancel,omitempty"`
	Start *bool `json:"start,omitempty"`
}

// NewSettingsJellyfinSyncPostRequest instantiates a new SettingsJellyfinSyncPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSettingsJellyfinSyncPostRequest() *SettingsJellyfinSyncPostRequest {
	this := SettingsJellyfinSyncPostRequest{}
	return &this
}

// NewSettingsJellyfinSyncPostRequestWithDefaults instantiates a new SettingsJellyfinSyncPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSettingsJellyfinSyncPostRequestWithDefaults() *SettingsJellyfinSyncPostRequest {
	this := SettingsJellyfinSyncPostRequest{}
	return &this
}

// GetCancel returns the Cancel field value if set, zero value otherwise.
func (o *SettingsJellyfinSyncPostRequest) GetCancel() bool {
	if o == nil || IsNil(o.Cancel) {
		var ret bool
		return ret
	}
	return *o.Cancel
}

// GetCancelOk returns a tuple with the Cancel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsJellyfinSyncPostRequest) GetCancelOk() (*bool, bool) {
	if o == nil || IsNil(o.Cancel) {
		return nil, false
	}
	return o.Cancel, true
}

// HasCancel returns a boolean if a field has been set.
func (o *SettingsJellyfinSyncPostRequest) HasCancel() bool {
	if o != nil && !IsNil(o.Cancel) {
		return true
	}

	return false
}

// SetCancel gets a reference to the given bool and assigns it to the Cancel field.
func (o *SettingsJellyfinSyncPostRequest) SetCancel(v bool) {
	o.Cancel = &v
}

// GetStart returns the Start field value if set, zero value otherwise.
func (o *SettingsJellyfinSyncPostRequest) GetStart() bool {
	if o == nil || IsNil(o.Start) {
		var ret bool
		return ret
	}
	return *o.Start
}

// GetStartOk returns a tuple with the Start field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsJellyfinSyncPostRequest) GetStartOk() (*bool, bool) {
	if o == nil || IsNil(o.Start) {
		return nil, false
	}
	return o.Start, true
}

// HasStart returns a boolean if a field has been set.
func (o *SettingsJellyfinSyncPostRequest) HasStart() bool {
	if o != nil && !IsNil(o.Start) {
		return true
	}

	return false
}

// SetStart gets a reference to the given bool and assigns it to the Start field.
func (o *SettingsJellyfinSyncPostRequest) SetStart(v bool) {
	o.Start = &v
}

func (o SettingsJellyfinSyncPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SettingsJellyfinSyncPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cancel) {
		toSerialize["cancel"] = o.Cancel
	}
	if !IsNil(o.Start) {
		toSerialize["start"] = o.Start
	}
	return toSerialize, nil
}

type NullableSettingsJellyfinSyncPostRequest struct {
	value *SettingsJellyfinSyncPostRequest
	isSet bool
}

func (v NullableSettingsJellyfinSyncPostRequest) Get() *SettingsJellyfinSyncPostRequest {
	return v.value
}

func (v *NullableSettingsJellyfinSyncPostRequest) Set(val *SettingsJellyfinSyncPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSettingsJellyfinSyncPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSettingsJellyfinSyncPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSettingsJellyfinSyncPostRequest(val *SettingsJellyfinSyncPostRequest) *NullableSettingsJellyfinSyncPostRequest {
	return &NullableSettingsJellyfinSyncPostRequest{value: val, isSet: true}
}

func (v NullableSettingsJellyfinSyncPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSettingsJellyfinSyncPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


