/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the SettingsJellyfinSyncGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SettingsJellyfinSyncGet200Response{}

// SettingsJellyfinSyncGet200Response struct for SettingsJellyfinSyncGet200Response
type SettingsJellyfinSyncGet200Response struct {
	Running *bool `json:"running,omitempty"`
	Progress *float32 `json:"progress,omitempty"`
	Total *float32 `json:"total,omitempty"`
	CurrentLibrary *JellyfinLibrary `json:"currentLibrary,omitempty"`
	Libraries []JellyfinLibrary `json:"libraries,omitempty"`
}

// NewSettingsJellyfinSyncGet200Response instantiates a new SettingsJellyfinSyncGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSettingsJellyfinSyncGet200Response() *SettingsJellyfinSyncGet200Response {
	this := SettingsJellyfinSyncGet200Response{}
	return &this
}

// NewSettingsJellyfinSyncGet200ResponseWithDefaults instantiates a new SettingsJellyfinSyncGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSettingsJellyfinSyncGet200ResponseWithDefaults() *SettingsJellyfinSyncGet200Response {
	this := SettingsJellyfinSyncGet200Response{}
	return &this
}

// GetRunning returns the Running field value if set, zero value otherwise.
func (o *SettingsJellyfinSyncGet200Response) GetRunning() bool {
	if o == nil || IsNil(o.Running) {
		var ret bool
		return ret
	}
	return *o.Running
}

// GetRunningOk returns a tuple with the Running field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsJellyfinSyncGet200Response) GetRunningOk() (*bool, bool) {
	if o == nil || IsNil(o.Running) {
		return nil, false
	}
	return o.Running, true
}

// HasRunning returns a boolean if a field has been set.
func (o *SettingsJellyfinSyncGet200Response) HasRunning() bool {
	if o != nil && !IsNil(o.Running) {
		return true
	}

	return false
}

// SetRunning gets a reference to the given bool and assigns it to the Running field.
func (o *SettingsJellyfinSyncGet200Response) SetRunning(v bool) {
	o.Running = &v
}

// GetProgress returns the Progress field value if set, zero value otherwise.
func (o *SettingsJellyfinSyncGet200Response) GetProgress() float32 {
	if o == nil || IsNil(o.Progress) {
		var ret float32
		return ret
	}
	return *o.Progress
}

// GetProgressOk returns a tuple with the Progress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsJellyfinSyncGet200Response) GetProgressOk() (*float32, bool) {
	if o == nil || IsNil(o.Progress) {
		return nil, false
	}
	return o.Progress, true
}

// HasProgress returns a boolean if a field has been set.
func (o *SettingsJellyfinSyncGet200Response) HasProgress() bool {
	if o != nil && !IsNil(o.Progress) {
		return true
	}

	return false
}

// SetProgress gets a reference to the given float32 and assigns it to the Progress field.
func (o *SettingsJellyfinSyncGet200Response) SetProgress(v float32) {
	o.Progress = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *SettingsJellyfinSyncGet200Response) GetTotal() float32 {
	if o == nil || IsNil(o.Total) {
		var ret float32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsJellyfinSyncGet200Response) GetTotalOk() (*float32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *SettingsJellyfinSyncGet200Response) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given float32 and assigns it to the Total field.
func (o *SettingsJellyfinSyncGet200Response) SetTotal(v float32) {
	o.Total = &v
}

// GetCurrentLibrary returns the CurrentLibrary field value if set, zero value otherwise.
func (o *SettingsJellyfinSyncGet200Response) GetCurrentLibrary() JellyfinLibrary {
	if o == nil || IsNil(o.CurrentLibrary) {
		var ret JellyfinLibrary
		return ret
	}
	return *o.CurrentLibrary
}

// GetCurrentLibraryOk returns a tuple with the CurrentLibrary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsJellyfinSyncGet200Response) GetCurrentLibraryOk() (*JellyfinLibrary, bool) {
	if o == nil || IsNil(o.CurrentLibrary) {
		return nil, false
	}
	return o.CurrentLibrary, true
}

// HasCurrentLibrary returns a boolean if a field has been set.
func (o *SettingsJellyfinSyncGet200Response) HasCurrentLibrary() bool {
	if o != nil && !IsNil(o.CurrentLibrary) {
		return true
	}

	return false
}

// SetCurrentLibrary gets a reference to the given JellyfinLibrary and assigns it to the CurrentLibrary field.
func (o *SettingsJellyfinSyncGet200Response) SetCurrentLibrary(v JellyfinLibrary) {
	o.CurrentLibrary = &v
}

// GetLibraries returns the Libraries field value if set, zero value otherwise.
func (o *SettingsJellyfinSyncGet200Response) GetLibraries() []JellyfinLibrary {
	if o == nil || IsNil(o.Libraries) {
		var ret []JellyfinLibrary
		return ret
	}
	return o.Libraries
}

// GetLibrariesOk returns a tuple with the Libraries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsJellyfinSyncGet200Response) GetLibrariesOk() ([]JellyfinLibrary, bool) {
	if o == nil || IsNil(o.Libraries) {
		return nil, false
	}
	return o.Libraries, true
}

// HasLibraries returns a boolean if a field has been set.
func (o *SettingsJellyfinSyncGet200Response) HasLibraries() bool {
	if o != nil && !IsNil(o.Libraries) {
		return true
	}

	return false
}

// SetLibraries gets a reference to the given []JellyfinLibrary and assigns it to the Libraries field.
func (o *SettingsJellyfinSyncGet200Response) SetLibraries(v []JellyfinLibrary) {
	o.Libraries = v
}

func (o SettingsJellyfinSyncGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SettingsJellyfinSyncGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Running) {
		toSerialize["running"] = o.Running
	}
	if !IsNil(o.Progress) {
		toSerialize["progress"] = o.Progress
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.CurrentLibrary) {
		toSerialize["currentLibrary"] = o.CurrentLibrary
	}
	if !IsNil(o.Libraries) {
		toSerialize["libraries"] = o.Libraries
	}
	return toSerialize, nil
}

type NullableSettingsJellyfinSyncGet200Response struct {
	value *SettingsJellyfinSyncGet200Response
	isSet bool
}

func (v NullableSettingsJellyfinSyncGet200Response) Get() *SettingsJellyfinSyncGet200Response {
	return v.value
}

func (v *NullableSettingsJellyfinSyncGet200Response) Set(val *SettingsJellyfinSyncGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableSettingsJellyfinSyncGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableSettingsJellyfinSyncGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSettingsJellyfinSyncGet200Response(val *SettingsJellyfinSyncGet200Response) *NullableSettingsJellyfinSyncGet200Response {
	return &NullableSettingsJellyfinSyncGet200Response{value: val, isSet: true}
}

func (v NullableSettingsJellyfinSyncGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSettingsJellyfinSyncGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


