/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the NetworkSettingsDnsCache type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkSettingsDnsCache{}

// NetworkSettingsDnsCache struct for NetworkSettingsDnsCache
type NetworkSettingsDnsCache struct {
	Enabled *bool `json:"enabled,omitempty"`
	ForceMinTtl *float32 `json:"forceMinTtl,omitempty"`
	ForceMaxTtl *float32 `json:"forceMaxTtl,omitempty"`
}

// NewNetworkSettingsDnsCache instantiates a new NetworkSettingsDnsCache object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkSettingsDnsCache() *NetworkSettingsDnsCache {
	this := NetworkSettingsDnsCache{}
	return &this
}

// NewNetworkSettingsDnsCacheWithDefaults instantiates a new NetworkSettingsDnsCache object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkSettingsDnsCacheWithDefaults() *NetworkSettingsDnsCache {
	this := NetworkSettingsDnsCache{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *NetworkSettingsDnsCache) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkSettingsDnsCache) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *NetworkSettingsDnsCache) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *NetworkSettingsDnsCache) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetForceMinTtl returns the ForceMinTtl field value if set, zero value otherwise.
func (o *NetworkSettingsDnsCache) GetForceMinTtl() float32 {
	if o == nil || IsNil(o.ForceMinTtl) {
		var ret float32
		return ret
	}
	return *o.ForceMinTtl
}

// GetForceMinTtlOk returns a tuple with the ForceMinTtl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkSettingsDnsCache) GetForceMinTtlOk() (*float32, bool) {
	if o == nil || IsNil(o.ForceMinTtl) {
		return nil, false
	}
	return o.ForceMinTtl, true
}

// HasForceMinTtl returns a boolean if a field has been set.
func (o *NetworkSettingsDnsCache) HasForceMinTtl() bool {
	if o != nil && !IsNil(o.ForceMinTtl) {
		return true
	}

	return false
}

// SetForceMinTtl gets a reference to the given float32 and assigns it to the ForceMinTtl field.
func (o *NetworkSettingsDnsCache) SetForceMinTtl(v float32) {
	o.ForceMinTtl = &v
}

// GetForceMaxTtl returns the ForceMaxTtl field value if set, zero value otherwise.
func (o *NetworkSettingsDnsCache) GetForceMaxTtl() float32 {
	if o == nil || IsNil(o.ForceMaxTtl) {
		var ret float32
		return ret
	}
	return *o.ForceMaxTtl
}

// GetForceMaxTtlOk returns a tuple with the ForceMaxTtl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkSettingsDnsCache) GetForceMaxTtlOk() (*float32, bool) {
	if o == nil || IsNil(o.ForceMaxTtl) {
		return nil, false
	}
	return o.ForceMaxTtl, true
}

// HasForceMaxTtl returns a boolean if a field has been set.
func (o *NetworkSettingsDnsCache) HasForceMaxTtl() bool {
	if o != nil && !IsNil(o.ForceMaxTtl) {
		return true
	}

	return false
}

// SetForceMaxTtl gets a reference to the given float32 and assigns it to the ForceMaxTtl field.
func (o *NetworkSettingsDnsCache) SetForceMaxTtl(v float32) {
	o.ForceMaxTtl = &v
}

func (o NetworkSettingsDnsCache) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkSettingsDnsCache) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.ForceMinTtl) {
		toSerialize["forceMinTtl"] = o.ForceMinTtl
	}
	if !IsNil(o.ForceMaxTtl) {
		toSerialize["forceMaxTtl"] = o.ForceMaxTtl
	}
	return toSerialize, nil
}

type NullableNetworkSettingsDnsCache struct {
	value *NetworkSettingsDnsCache
	isSet bool
}

func (v NullableNetworkSettingsDnsCache) Get() *NetworkSettingsDnsCache {
	return v.value
}

func (v *NullableNetworkSettingsDnsCache) Set(val *NetworkSettingsDnsCache) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkSettingsDnsCache) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkSettingsDnsCache) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkSettingsDnsCache(val *NetworkSettingsDnsCache) *NullableNetworkSettingsDnsCache {
	return &NullableNetworkSettingsDnsCache{value: val, isSet: true}
}

func (v NullableNetworkSettingsDnsCache) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkSettingsDnsCache) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


