/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JellyfinLibrary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JellyfinLibrary{}

// JellyfinLibrary struct for JellyfinLibrary
type JellyfinLibrary struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Enabled bool `json:"enabled"`
}

type _JellyfinLibrary JellyfinLibrary

// NewJellyfinLibrary instantiates a new JellyfinLibrary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJellyfinLibrary(id string, name string, enabled bool) *JellyfinLibrary {
	this := JellyfinLibrary{}
	this.Id = id
	this.Name = name
	this.Enabled = enabled
	return &this
}

// NewJellyfinLibraryWithDefaults instantiates a new JellyfinLibrary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJellyfinLibraryWithDefaults() *JellyfinLibrary {
	this := JellyfinLibrary{}
	return &this
}

// GetId returns the Id field value
func (o *JellyfinLibrary) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *JellyfinLibrary) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *JellyfinLibrary) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *JellyfinLibrary) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *JellyfinLibrary) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *JellyfinLibrary) SetName(v string) {
	o.Name = v
}

// GetEnabled returns the Enabled field value
func (o *JellyfinLibrary) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *JellyfinLibrary) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *JellyfinLibrary) SetEnabled(v bool) {
	o.Enabled = v
}

func (o JellyfinLibrary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JellyfinLibrary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["enabled"] = o.Enabled
	return toSerialize, nil
}

func (o *JellyfinLibrary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"enabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJellyfinLibrary := _JellyfinLibrary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJellyfinLibrary)

	if err != nil {
		return err
	}

	*o = JellyfinLibrary(varJellyfinLibrary)

	return err
}

type NullableJellyfinLibrary struct {
	value *JellyfinLibrary
	isSet bool
}

func (v NullableJellyfinLibrary) Get() *JellyfinLibrary {
	return v.value
}

func (v *NullableJellyfinLibrary) Set(val *JellyfinLibrary) {
	v.value = val
	v.isSet = true
}

func (v NullableJellyfinLibrary) IsSet() bool {
	return v.isSet
}

func (v *NullableJellyfinLibrary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJellyfinLibrary(val *JellyfinLibrary) *NullableJellyfinLibrary {
	return &NullableJellyfinLibrary{value: val, isSet: true}
}

func (v NullableJellyfinLibrary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJellyfinLibrary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


