/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the CertificationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CertificationResponse{}

// CertificationResponse struct for CertificationResponse
type CertificationResponse struct {
	Certifications *map[string][]Certification `json:"certifications,omitempty"`
}

// NewCertificationResponse instantiates a new CertificationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCertificationResponse() *CertificationResponse {
	this := CertificationResponse{}
	return &this
}

// NewCertificationResponseWithDefaults instantiates a new CertificationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCertificationResponseWithDefaults() *CertificationResponse {
	this := CertificationResponse{}
	return &this
}

// GetCertifications returns the Certifications field value if set, zero value otherwise.
func (o *CertificationResponse) GetCertifications() map[string][]Certification {
	if o == nil || IsNil(o.Certifications) {
		var ret map[string][]Certification
		return ret
	}
	return *o.Certifications
}

// GetCertificationsOk returns a tuple with the Certifications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificationResponse) GetCertificationsOk() (*map[string][]Certification, bool) {
	if o == nil || IsNil(o.Certifications) {
		return nil, false
	}
	return o.Certifications, true
}

// HasCertifications returns a boolean if a field has been set.
func (o *CertificationResponse) HasCertifications() bool {
	if o != nil && !IsNil(o.Certifications) {
		return true
	}

	return false
}

// SetCertifications gets a reference to the given map[string][]Certification and assigns it to the Certifications field.
func (o *CertificationResponse) SetCertifications(v map[string][]Certification) {
	o.Certifications = &v
}

func (o CertificationResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CertificationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Certifications) {
		toSerialize["certifications"] = o.Certifications
	}
	return toSerialize, nil
}

type NullableCertificationResponse struct {
	value *CertificationResponse
	isSet bool
}

func (v NullableCertificationResponse) Get() *CertificationResponse {
	return v.value
}

func (v *NullableCertificationResponse) Set(val *CertificationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCertificationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCertificationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertificationResponse(val *CertificationResponse) *NullableCertificationResponse {
	return &NullableCertificationResponse{value: val, isSet: true}
}

func (v NullableCertificationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertificationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


