/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the SettingsCacheGet200ResponseDnsCacheStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SettingsCacheGet200ResponseDnsCacheStats{}

// SettingsCacheGet200ResponseDnsCacheStats struct for SettingsCacheGet200ResponseDnsCacheStats
type SettingsCacheGet200ResponseDnsCacheStats struct {
	Size *float32 `json:"size,omitempty"`
	MaxSize *float32 `json:"maxSize,omitempty"`
	Hits *float32 `json:"hits,omitempty"`
	Misses *float32 `json:"misses,omitempty"`
	Failures *float32 `json:"failures,omitempty"`
	Ipv4Fallbacks *float32 `json:"ipv4Fallbacks,omitempty"`
	HitRate *float32 `json:"hitRate,omitempty"`
}

// NewSettingsCacheGet200ResponseDnsCacheStats instantiates a new SettingsCacheGet200ResponseDnsCacheStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSettingsCacheGet200ResponseDnsCacheStats() *SettingsCacheGet200ResponseDnsCacheStats {
	this := SettingsCacheGet200ResponseDnsCacheStats{}
	return &this
}

// NewSettingsCacheGet200ResponseDnsCacheStatsWithDefaults instantiates a new SettingsCacheGet200ResponseDnsCacheStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSettingsCacheGet200ResponseDnsCacheStatsWithDefaults() *SettingsCacheGet200ResponseDnsCacheStats {
	this := SettingsCacheGet200ResponseDnsCacheStats{}
	return &this
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *SettingsCacheGet200ResponseDnsCacheStats) GetSize() float32 {
	if o == nil || IsNil(o.Size) {
		var ret float32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsCacheGet200ResponseDnsCacheStats) GetSizeOk() (*float32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *SettingsCacheGet200ResponseDnsCacheStats) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given float32 and assigns it to the Size field.
func (o *SettingsCacheGet200ResponseDnsCacheStats) SetSize(v float32) {
	o.Size = &v
}

// GetMaxSize returns the MaxSize field value if set, zero value otherwise.
func (o *SettingsCacheGet200ResponseDnsCacheStats) GetMaxSize() float32 {
	if o == nil || IsNil(o.MaxSize) {
		var ret float32
		return ret
	}
	return *o.MaxSize
}

// GetMaxSizeOk returns a tuple with the MaxSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsCacheGet200ResponseDnsCacheStats) GetMaxSizeOk() (*float32, bool) {
	if o == nil || IsNil(o.MaxSize) {
		return nil, false
	}
	return o.MaxSize, true
}

// HasMaxSize returns a boolean if a field has been set.
func (o *SettingsCacheGet200ResponseDnsCacheStats) HasMaxSize() bool {
	if o != nil && !IsNil(o.MaxSize) {
		return true
	}

	return false
}

// SetMaxSize gets a reference to the given float32 and assigns it to the MaxSize field.
func (o *SettingsCacheGet200ResponseDnsCacheStats) SetMaxSize(v float32) {
	o.MaxSize = &v
}

// GetHits returns the Hits field value if set, zero value otherwise.
func (o *SettingsCacheGet200ResponseDnsCacheStats) GetHits() float32 {
	if o == nil || IsNil(o.Hits) {
		var ret float32
		return ret
	}
	return *o.Hits
}

// GetHitsOk returns a tuple with the Hits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsCacheGet200ResponseDnsCacheStats) GetHitsOk() (*float32, bool) {
	if o == nil || IsNil(o.Hits) {
		return nil, false
	}
	return o.Hits, true
}

// HasHits returns a boolean if a field has been set.
func (o *SettingsCacheGet200ResponseDnsCacheStats) HasHits() bool {
	if o != nil && !IsNil(o.Hits) {
		return true
	}

	return false
}

// SetHits gets a reference to the given float32 and assigns it to the Hits field.
func (o *SettingsCacheGet200ResponseDnsCacheStats) SetHits(v float32) {
	o.Hits = &v
}

// GetMisses returns the Misses field value if set, zero value otherwise.
func (o *SettingsCacheGet200ResponseDnsCacheStats) GetMisses() float32 {
	if o == nil || IsNil(o.Misses) {
		var ret float32
		return ret
	}
	return *o.Misses
}

// GetMissesOk returns a tuple with the Misses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsCacheGet200ResponseDnsCacheStats) GetMissesOk() (*float32, bool) {
	if o == nil || IsNil(o.Misses) {
		return nil, false
	}
	return o.Misses, true
}

// HasMisses returns a boolean if a field has been set.
func (o *SettingsCacheGet200ResponseDnsCacheStats) HasMisses() bool {
	if o != nil && !IsNil(o.Misses) {
		return true
	}

	return false
}

// SetMisses gets a reference to the given float32 and assigns it to the Misses field.
func (o *SettingsCacheGet200ResponseDnsCacheStats) SetMisses(v float32) {
	o.Misses = &v
}

// GetFailures returns the Failures field value if set, zero value otherwise.
func (o *SettingsCacheGet200ResponseDnsCacheStats) GetFailures() float32 {
	if o == nil || IsNil(o.Failures) {
		var ret float32
		return ret
	}
	return *o.Failures
}

// GetFailuresOk returns a tuple with the Failures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsCacheGet200ResponseDnsCacheStats) GetFailuresOk() (*float32, bool) {
	if o == nil || IsNil(o.Failures) {
		return nil, false
	}
	return o.Failures, true
}

// HasFailures returns a boolean if a field has been set.
func (o *SettingsCacheGet200ResponseDnsCacheStats) HasFailures() bool {
	if o != nil && !IsNil(o.Failures) {
		return true
	}

	return false
}

// SetFailures gets a reference to the given float32 and assigns it to the Failures field.
func (o *SettingsCacheGet200ResponseDnsCacheStats) SetFailures(v float32) {
	o.Failures = &v
}

// GetIpv4Fallbacks returns the Ipv4Fallbacks field value if set, zero value otherwise.
func (o *SettingsCacheGet200ResponseDnsCacheStats) GetIpv4Fallbacks() float32 {
	if o == nil || IsNil(o.Ipv4Fallbacks) {
		var ret float32
		return ret
	}
	return *o.Ipv4Fallbacks
}

// GetIpv4FallbacksOk returns a tuple with the Ipv4Fallbacks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsCacheGet200ResponseDnsCacheStats) GetIpv4FallbacksOk() (*float32, bool) {
	if o == nil || IsNil(o.Ipv4Fallbacks) {
		return nil, false
	}
	return o.Ipv4Fallbacks, true
}

// HasIpv4Fallbacks returns a boolean if a field has been set.
func (o *SettingsCacheGet200ResponseDnsCacheStats) HasIpv4Fallbacks() bool {
	if o != nil && !IsNil(o.Ipv4Fallbacks) {
		return true
	}

	return false
}

// SetIpv4Fallbacks gets a reference to the given float32 and assigns it to the Ipv4Fallbacks field.
func (o *SettingsCacheGet200ResponseDnsCacheStats) SetIpv4Fallbacks(v float32) {
	o.Ipv4Fallbacks = &v
}

// GetHitRate returns the HitRate field value if set, zero value otherwise.
func (o *SettingsCacheGet200ResponseDnsCacheStats) GetHitRate() float32 {
	if o == nil || IsNil(o.HitRate) {
		var ret float32
		return ret
	}
	return *o.HitRate
}

// GetHitRateOk returns a tuple with the HitRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsCacheGet200ResponseDnsCacheStats) GetHitRateOk() (*float32, bool) {
	if o == nil || IsNil(o.HitRate) {
		return nil, false
	}
	return o.HitRate, true
}

// HasHitRate returns a boolean if a field has been set.
func (o *SettingsCacheGet200ResponseDnsCacheStats) HasHitRate() bool {
	if o != nil && !IsNil(o.HitRate) {
		return true
	}

	return false
}

// SetHitRate gets a reference to the given float32 and assigns it to the HitRate field.
func (o *SettingsCacheGet200ResponseDnsCacheStats) SetHitRate(v float32) {
	o.HitRate = &v
}

func (o SettingsCacheGet200ResponseDnsCacheStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SettingsCacheGet200ResponseDnsCacheStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.MaxSize) {
		toSerialize["maxSize"] = o.MaxSize
	}
	if !IsNil(o.Hits) {
		toSerialize["hits"] = o.Hits
	}
	if !IsNil(o.Misses) {
		toSerialize["misses"] = o.Misses
	}
	if !IsNil(o.Failures) {
		toSerialize["failures"] = o.Failures
	}
	if !IsNil(o.Ipv4Fallbacks) {
		toSerialize["ipv4Fallbacks"] = o.Ipv4Fallbacks
	}
	if !IsNil(o.HitRate) {
		toSerialize["hitRate"] = o.HitRate
	}
	return toSerialize, nil
}

type NullableSettingsCacheGet200ResponseDnsCacheStats struct {
	value *SettingsCacheGet200ResponseDnsCacheStats
	isSet bool
}

func (v NullableSettingsCacheGet200ResponseDnsCacheStats) Get() *SettingsCacheGet200ResponseDnsCacheStats {
	return v.value
}

func (v *NullableSettingsCacheGet200ResponseDnsCacheStats) Set(val *SettingsCacheGet200ResponseDnsCacheStats) {
	v.value = val
	v.isSet = true
}

func (v NullableSettingsCacheGet200ResponseDnsCacheStats) IsSet() bool {
	return v.isSet
}

func (v *NullableSettingsCacheGet200ResponseDnsCacheStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSettingsCacheGet200ResponseDnsCacheStats(val *SettingsCacheGet200ResponseDnsCacheStats) *NullableSettingsCacheGet200ResponseDnsCacheStats {
	return &NullableSettingsCacheGet200ResponseDnsCacheStats{value: val, isSet: true}
}

func (v NullableSettingsCacheGet200ResponseDnsCacheStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSettingsCacheGet200ResponseDnsCacheStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


