/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the SettingsCacheGet200ResponseDnsCache type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SettingsCacheGet200ResponseDnsCache{}

// SettingsCacheGet200ResponseDnsCache struct for SettingsCacheGet200ResponseDnsCache
type SettingsCacheGet200ResponseDnsCache struct {
	Stats *SettingsCacheGet200ResponseDnsCacheStats `json:"stats,omitempty"`
	Entries *map[string]SettingsCacheGet200ResponseDnsCacheEntriesValue `json:"entries,omitempty"`
}

// NewSettingsCacheGet200ResponseDnsCache instantiates a new SettingsCacheGet200ResponseDnsCache object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSettingsCacheGet200ResponseDnsCache() *SettingsCacheGet200ResponseDnsCache {
	this := SettingsCacheGet200ResponseDnsCache{}
	return &this
}

// NewSettingsCacheGet200ResponseDnsCacheWithDefaults instantiates a new SettingsCacheGet200ResponseDnsCache object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSettingsCacheGet200ResponseDnsCacheWithDefaults() *SettingsCacheGet200ResponseDnsCache {
	this := SettingsCacheGet200ResponseDnsCache{}
	return &this
}

// GetStats returns the Stats field value if set, zero value otherwise.
func (o *SettingsCacheGet200ResponseDnsCache) GetStats() SettingsCacheGet200ResponseDnsCacheStats {
	if o == nil || IsNil(o.Stats) {
		var ret SettingsCacheGet200ResponseDnsCacheStats
		return ret
	}
	return *o.Stats
}

// GetStatsOk returns a tuple with the Stats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsCacheGet200ResponseDnsCache) GetStatsOk() (*SettingsCacheGet200ResponseDnsCacheStats, bool) {
	if o == nil || IsNil(o.Stats) {
		return nil, false
	}
	return o.Stats, true
}

// HasStats returns a boolean if a field has been set.
func (o *SettingsCacheGet200ResponseDnsCache) HasStats() bool {
	if o != nil && !IsNil(o.Stats) {
		return true
	}

	return false
}

// SetStats gets a reference to the given SettingsCacheGet200ResponseDnsCacheStats and assigns it to the Stats field.
func (o *SettingsCacheGet200ResponseDnsCache) SetStats(v SettingsCacheGet200ResponseDnsCacheStats) {
	o.Stats = &v
}

// GetEntries returns the Entries field value if set, zero value otherwise.
func (o *SettingsCacheGet200ResponseDnsCache) GetEntries() map[string]SettingsCacheGet200ResponseDnsCacheEntriesValue {
	if o == nil || IsNil(o.Entries) {
		var ret map[string]SettingsCacheGet200ResponseDnsCacheEntriesValue
		return ret
	}
	return *o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsCacheGet200ResponseDnsCache) GetEntriesOk() (*map[string]SettingsCacheGet200ResponseDnsCacheEntriesValue, bool) {
	if o == nil || IsNil(o.Entries) {
		return nil, false
	}
	return o.Entries, true
}

// HasEntries returns a boolean if a field has been set.
func (o *SettingsCacheGet200ResponseDnsCache) HasEntries() bool {
	if o != nil && !IsNil(o.Entries) {
		return true
	}

	return false
}

// SetEntries gets a reference to the given map[string]SettingsCacheGet200ResponseDnsCacheEntriesValue and assigns it to the Entries field.
func (o *SettingsCacheGet200ResponseDnsCache) SetEntries(v map[string]SettingsCacheGet200ResponseDnsCacheEntriesValue) {
	o.Entries = &v
}

func (o SettingsCacheGet200ResponseDnsCache) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SettingsCacheGet200ResponseDnsCache) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Stats) {
		toSerialize["stats"] = o.Stats
	}
	if !IsNil(o.Entries) {
		toSerialize["entries"] = o.Entries
	}
	return toSerialize, nil
}

type NullableSettingsCacheGet200ResponseDnsCache struct {
	value *SettingsCacheGet200ResponseDnsCache
	isSet bool
}

func (v NullableSettingsCacheGet200ResponseDnsCache) Get() *SettingsCacheGet200ResponseDnsCache {
	return v.value
}

func (v *NullableSettingsCacheGet200ResponseDnsCache) Set(val *SettingsCacheGet200ResponseDnsCache) {
	v.value = val
	v.isSet = true
}

func (v NullableSettingsCacheGet200ResponseDnsCache) IsSet() bool {
	return v.isSet
}

func (v *NullableSettingsCacheGet200ResponseDnsCache) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSettingsCacheGet200ResponseDnsCache(val *SettingsCacheGet200ResponseDnsCache) *NullableSettingsCacheGet200ResponseDnsCache {
	return &NullableSettingsCacheGet200ResponseDnsCache{value: val, isSet: true}
}

func (v NullableSettingsCacheGet200ResponseDnsCache) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSettingsCacheGet200ResponseDnsCache) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


