/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Certification type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Certification{}

// Certification struct for Certification
type Certification struct {
	Certification string `json:"certification"`
	Meaning NullableString `json:"meaning,omitempty"`
	Order NullableFloat32 `json:"order,omitempty"`
}

type _Certification Certification

// NewCertification instantiates a new Certification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCertification(certification string) *Certification {
	this := Certification{}
	this.Certification = certification
	return &this
}

// NewCertificationWithDefaults instantiates a new Certification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCertificationWithDefaults() *Certification {
	this := Certification{}
	return &this
}

// GetCertification returns the Certification field value
func (o *Certification) GetCertification() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Certification
}

// GetCertificationOk returns a tuple with the Certification field value
// and a boolean to check if the value has been set.
func (o *Certification) GetCertificationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Certification, true
}

// SetCertification sets field value
func (o *Certification) SetCertification(v string) {
	o.Certification = v
}

// GetMeaning returns the Meaning field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Certification) GetMeaning() string {
	if o == nil || IsNil(o.Meaning.Get()) {
		var ret string
		return ret
	}
	return *o.Meaning.Get()
}

// GetMeaningOk returns a tuple with the Meaning field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Certification) GetMeaningOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Meaning.Get(), o.Meaning.IsSet()
}

// HasMeaning returns a boolean if a field has been set.
func (o *Certification) HasMeaning() bool {
	if o != nil && o.Meaning.IsSet() {
		return true
	}

	return false
}

// SetMeaning gets a reference to the given NullableString and assigns it to the Meaning field.
func (o *Certification) SetMeaning(v string) {
	o.Meaning.Set(&v)
}
// SetMeaningNil sets the value for Meaning to be an explicit nil
func (o *Certification) SetMeaningNil() {
	o.Meaning.Set(nil)
}

// UnsetMeaning ensures that no value is present for Meaning, not even an explicit nil
func (o *Certification) UnsetMeaning() {
	o.Meaning.Unset()
}

// GetOrder returns the Order field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Certification) GetOrder() float32 {
	if o == nil || IsNil(o.Order.Get()) {
		var ret float32
		return ret
	}
	return *o.Order.Get()
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Certification) GetOrderOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Order.Get(), o.Order.IsSet()
}

// HasOrder returns a boolean if a field has been set.
func (o *Certification) HasOrder() bool {
	if o != nil && o.Order.IsSet() {
		return true
	}

	return false
}

// SetOrder gets a reference to the given NullableFloat32 and assigns it to the Order field.
func (o *Certification) SetOrder(v float32) {
	o.Order.Set(&v)
}
// SetOrderNil sets the value for Order to be an explicit nil
func (o *Certification) SetOrderNil() {
	o.Order.Set(nil)
}

// UnsetOrder ensures that no value is present for Order, not even an explicit nil
func (o *Certification) UnsetOrder() {
	o.Order.Unset()
}

func (o Certification) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Certification) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["certification"] = o.Certification
	if o.Meaning.IsSet() {
		toSerialize["meaning"] = o.Meaning.Get()
	}
	if o.Order.IsSet() {
		toSerialize["order"] = o.Order.Get()
	}
	return toSerialize, nil
}

func (o *Certification) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"certification",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCertification := _Certification{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCertification)

	if err != nil {
		return err
	}

	*o = Certification(varCertification)

	return err
}

type NullableCertification struct {
	value *Certification
	isSet bool
}

func (v NullableCertification) Get() *Certification {
	return v.value
}

func (v *NullableCertification) Set(val *Certification) {
	v.value = val
	v.isSet = true
}

func (v NullableCertification) IsSet() bool {
	return v.isSet
}

func (v *NullableCertification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertification(val *Certification) *NullableCertification {
	return &NullableCertification{value: val, isSet: true}
}

func (v NullableCertification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


