/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the UserSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserSettings{}

// UserSettings struct for UserSettings
type UserSettings struct {
	Username NullableString `json:"username,omitempty"`
	Email *string `json:"email,omitempty"`
	DiscordId NullableString `json:"discordId,omitempty"`
	Locale NullableString `json:"locale,omitempty"`
	DiscoverRegion NullableString `json:"discoverRegion,omitempty"`
	StreamingRegion NullableString `json:"streamingRegion,omitempty"`
	OriginalLanguage NullableString `json:"originalLanguage,omitempty"`
	// Maximum number of movie requests allowed
	MovieQuotaLimit NullableFloat32 `json:"movieQuotaLimit,omitempty"`
	// Time period in days for movie quota
	MovieQuotaDays NullableFloat32 `json:"movieQuotaDays,omitempty"`
	// Maximum number of TV requests allowed
	TvQuotaLimit NullableFloat32 `json:"tvQuotaLimit,omitempty"`
	// Time period in days for TV quota
	TvQuotaDays NullableFloat32 `json:"tvQuotaDays,omitempty"`
	// Global movie quota days setting
	GlobalMovieQuotaDays NullableFloat32 `json:"globalMovieQuotaDays,omitempty"`
	// Global movie quota limit setting
	GlobalMovieQuotaLimit NullableFloat32 `json:"globalMovieQuotaLimit,omitempty"`
	// Global TV quota limit setting
	GlobalTvQuotaLimit NullableFloat32 `json:"globalTvQuotaLimit,omitempty"`
	// Global TV quota days setting
	GlobalTvQuotaDays NullableFloat32 `json:"globalTvQuotaDays,omitempty"`
	// Enable watchlist sync for movies
	WatchlistSyncMovies NullableBool `json:"watchlistSyncMovies,omitempty"`
	// Enable watchlist sync for TV
	WatchlistSyncTv NullableBool `json:"watchlistSyncTv,omitempty"`
}

// NewUserSettings instantiates a new UserSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserSettings() *UserSettings {
	this := UserSettings{}
	return &this
}

// NewUserSettingsWithDefaults instantiates a new UserSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserSettingsWithDefaults() *UserSettings {
	this := UserSettings{}
	return &this
}

// GetUsername returns the Username field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserSettings) GetUsername() string {
	if o == nil || IsNil(o.Username.Get()) {
		var ret string
		return ret
	}
	return *o.Username.Get()
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserSettings) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Username.Get(), o.Username.IsSet()
}

// HasUsername returns a boolean if a field has been set.
func (o *UserSettings) HasUsername() bool {
	if o != nil && o.Username.IsSet() {
		return true
	}

	return false
}

// SetUsername gets a reference to the given NullableString and assigns it to the Username field.
func (o *UserSettings) SetUsername(v string) {
	o.Username.Set(&v)
}
// SetUsernameNil sets the value for Username to be an explicit nil
func (o *UserSettings) SetUsernameNil() {
	o.Username.Set(nil)
}

// UnsetUsername ensures that no value is present for Username, not even an explicit nil
func (o *UserSettings) UnsetUsername() {
	o.Username.Unset()
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *UserSettings) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettings) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *UserSettings) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *UserSettings) SetEmail(v string) {
	o.Email = &v
}

// GetDiscordId returns the DiscordId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserSettings) GetDiscordId() string {
	if o == nil || IsNil(o.DiscordId.Get()) {
		var ret string
		return ret
	}
	return *o.DiscordId.Get()
}

// GetDiscordIdOk returns a tuple with the DiscordId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserSettings) GetDiscordIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DiscordId.Get(), o.DiscordId.IsSet()
}

// HasDiscordId returns a boolean if a field has been set.
func (o *UserSettings) HasDiscordId() bool {
	if o != nil && o.DiscordId.IsSet() {
		return true
	}

	return false
}

// SetDiscordId gets a reference to the given NullableString and assigns it to the DiscordId field.
func (o *UserSettings) SetDiscordId(v string) {
	o.DiscordId.Set(&v)
}
// SetDiscordIdNil sets the value for DiscordId to be an explicit nil
func (o *UserSettings) SetDiscordIdNil() {
	o.DiscordId.Set(nil)
}

// UnsetDiscordId ensures that no value is present for DiscordId, not even an explicit nil
func (o *UserSettings) UnsetDiscordId() {
	o.DiscordId.Unset()
}

// GetLocale returns the Locale field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserSettings) GetLocale() string {
	if o == nil || IsNil(o.Locale.Get()) {
		var ret string
		return ret
	}
	return *o.Locale.Get()
}

// GetLocaleOk returns a tuple with the Locale field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserSettings) GetLocaleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Locale.Get(), o.Locale.IsSet()
}

// HasLocale returns a boolean if a field has been set.
func (o *UserSettings) HasLocale() bool {
	if o != nil && o.Locale.IsSet() {
		return true
	}

	return false
}

// SetLocale gets a reference to the given NullableString and assigns it to the Locale field.
func (o *UserSettings) SetLocale(v string) {
	o.Locale.Set(&v)
}
// SetLocaleNil sets the value for Locale to be an explicit nil
func (o *UserSettings) SetLocaleNil() {
	o.Locale.Set(nil)
}

// UnsetLocale ensures that no value is present for Locale, not even an explicit nil
func (o *UserSettings) UnsetLocale() {
	o.Locale.Unset()
}

// GetDiscoverRegion returns the DiscoverRegion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserSettings) GetDiscoverRegion() string {
	if o == nil || IsNil(o.DiscoverRegion.Get()) {
		var ret string
		return ret
	}
	return *o.DiscoverRegion.Get()
}

// GetDiscoverRegionOk returns a tuple with the DiscoverRegion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserSettings) GetDiscoverRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DiscoverRegion.Get(), o.DiscoverRegion.IsSet()
}

// HasDiscoverRegion returns a boolean if a field has been set.
func (o *UserSettings) HasDiscoverRegion() bool {
	if o != nil && o.DiscoverRegion.IsSet() {
		return true
	}

	return false
}

// SetDiscoverRegion gets a reference to the given NullableString and assigns it to the DiscoverRegion field.
func (o *UserSettings) SetDiscoverRegion(v string) {
	o.DiscoverRegion.Set(&v)
}
// SetDiscoverRegionNil sets the value for DiscoverRegion to be an explicit nil
func (o *UserSettings) SetDiscoverRegionNil() {
	o.DiscoverRegion.Set(nil)
}

// UnsetDiscoverRegion ensures that no value is present for DiscoverRegion, not even an explicit nil
func (o *UserSettings) UnsetDiscoverRegion() {
	o.DiscoverRegion.Unset()
}

// GetStreamingRegion returns the StreamingRegion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserSettings) GetStreamingRegion() string {
	if o == nil || IsNil(o.StreamingRegion.Get()) {
		var ret string
		return ret
	}
	return *o.StreamingRegion.Get()
}

// GetStreamingRegionOk returns a tuple with the StreamingRegion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserSettings) GetStreamingRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StreamingRegion.Get(), o.StreamingRegion.IsSet()
}

// HasStreamingRegion returns a boolean if a field has been set.
func (o *UserSettings) HasStreamingRegion() bool {
	if o != nil && o.StreamingRegion.IsSet() {
		return true
	}

	return false
}

// SetStreamingRegion gets a reference to the given NullableString and assigns it to the StreamingRegion field.
func (o *UserSettings) SetStreamingRegion(v string) {
	o.StreamingRegion.Set(&v)
}
// SetStreamingRegionNil sets the value for StreamingRegion to be an explicit nil
func (o *UserSettings) SetStreamingRegionNil() {
	o.StreamingRegion.Set(nil)
}

// UnsetStreamingRegion ensures that no value is present for StreamingRegion, not even an explicit nil
func (o *UserSettings) UnsetStreamingRegion() {
	o.StreamingRegion.Unset()
}

// GetOriginalLanguage returns the OriginalLanguage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserSettings) GetOriginalLanguage() string {
	if o == nil || IsNil(o.OriginalLanguage.Get()) {
		var ret string
		return ret
	}
	return *o.OriginalLanguage.Get()
}

// GetOriginalLanguageOk returns a tuple with the OriginalLanguage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserSettings) GetOriginalLanguageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OriginalLanguage.Get(), o.OriginalLanguage.IsSet()
}

// HasOriginalLanguage returns a boolean if a field has been set.
func (o *UserSettings) HasOriginalLanguage() bool {
	if o != nil && o.OriginalLanguage.IsSet() {
		return true
	}

	return false
}

// SetOriginalLanguage gets a reference to the given NullableString and assigns it to the OriginalLanguage field.
func (o *UserSettings) SetOriginalLanguage(v string) {
	o.OriginalLanguage.Set(&v)
}
// SetOriginalLanguageNil sets the value for OriginalLanguage to be an explicit nil
func (o *UserSettings) SetOriginalLanguageNil() {
	o.OriginalLanguage.Set(nil)
}

// UnsetOriginalLanguage ensures that no value is present for OriginalLanguage, not even an explicit nil
func (o *UserSettings) UnsetOriginalLanguage() {
	o.OriginalLanguage.Unset()
}

// GetMovieQuotaLimit returns the MovieQuotaLimit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserSettings) GetMovieQuotaLimit() float32 {
	if o == nil || IsNil(o.MovieQuotaLimit.Get()) {
		var ret float32
		return ret
	}
	return *o.MovieQuotaLimit.Get()
}

// GetMovieQuotaLimitOk returns a tuple with the MovieQuotaLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserSettings) GetMovieQuotaLimitOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MovieQuotaLimit.Get(), o.MovieQuotaLimit.IsSet()
}

// HasMovieQuotaLimit returns a boolean if a field has been set.
func (o *UserSettings) HasMovieQuotaLimit() bool {
	if o != nil && o.MovieQuotaLimit.IsSet() {
		return true
	}

	return false
}

// SetMovieQuotaLimit gets a reference to the given NullableFloat32 and assigns it to the MovieQuotaLimit field.
func (o *UserSettings) SetMovieQuotaLimit(v float32) {
	o.MovieQuotaLimit.Set(&v)
}
// SetMovieQuotaLimitNil sets the value for MovieQuotaLimit to be an explicit nil
func (o *UserSettings) SetMovieQuotaLimitNil() {
	o.MovieQuotaLimit.Set(nil)
}

// UnsetMovieQuotaLimit ensures that no value is present for MovieQuotaLimit, not even an explicit nil
func (o *UserSettings) UnsetMovieQuotaLimit() {
	o.MovieQuotaLimit.Unset()
}

// GetMovieQuotaDays returns the MovieQuotaDays field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserSettings) GetMovieQuotaDays() float32 {
	if o == nil || IsNil(o.MovieQuotaDays.Get()) {
		var ret float32
		return ret
	}
	return *o.MovieQuotaDays.Get()
}

// GetMovieQuotaDaysOk returns a tuple with the MovieQuotaDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserSettings) GetMovieQuotaDaysOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MovieQuotaDays.Get(), o.MovieQuotaDays.IsSet()
}

// HasMovieQuotaDays returns a boolean if a field has been set.
func (o *UserSettings) HasMovieQuotaDays() bool {
	if o != nil && o.MovieQuotaDays.IsSet() {
		return true
	}

	return false
}

// SetMovieQuotaDays gets a reference to the given NullableFloat32 and assigns it to the MovieQuotaDays field.
func (o *UserSettings) SetMovieQuotaDays(v float32) {
	o.MovieQuotaDays.Set(&v)
}
// SetMovieQuotaDaysNil sets the value for MovieQuotaDays to be an explicit nil
func (o *UserSettings) SetMovieQuotaDaysNil() {
	o.MovieQuotaDays.Set(nil)
}

// UnsetMovieQuotaDays ensures that no value is present for MovieQuotaDays, not even an explicit nil
func (o *UserSettings) UnsetMovieQuotaDays() {
	o.MovieQuotaDays.Unset()
}

// GetTvQuotaLimit returns the TvQuotaLimit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserSettings) GetTvQuotaLimit() float32 {
	if o == nil || IsNil(o.TvQuotaLimit.Get()) {
		var ret float32
		return ret
	}
	return *o.TvQuotaLimit.Get()
}

// GetTvQuotaLimitOk returns a tuple with the TvQuotaLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserSettings) GetTvQuotaLimitOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TvQuotaLimit.Get(), o.TvQuotaLimit.IsSet()
}

// HasTvQuotaLimit returns a boolean if a field has been set.
func (o *UserSettings) HasTvQuotaLimit() bool {
	if o != nil && o.TvQuotaLimit.IsSet() {
		return true
	}

	return false
}

// SetTvQuotaLimit gets a reference to the given NullableFloat32 and assigns it to the TvQuotaLimit field.
func (o *UserSettings) SetTvQuotaLimit(v float32) {
	o.TvQuotaLimit.Set(&v)
}
// SetTvQuotaLimitNil sets the value for TvQuotaLimit to be an explicit nil
func (o *UserSettings) SetTvQuotaLimitNil() {
	o.TvQuotaLimit.Set(nil)
}

// UnsetTvQuotaLimit ensures that no value is present for TvQuotaLimit, not even an explicit nil
func (o *UserSettings) UnsetTvQuotaLimit() {
	o.TvQuotaLimit.Unset()
}

// GetTvQuotaDays returns the TvQuotaDays field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserSettings) GetTvQuotaDays() float32 {
	if o == nil || IsNil(o.TvQuotaDays.Get()) {
		var ret float32
		return ret
	}
	return *o.TvQuotaDays.Get()
}

// GetTvQuotaDaysOk returns a tuple with the TvQuotaDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserSettings) GetTvQuotaDaysOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TvQuotaDays.Get(), o.TvQuotaDays.IsSet()
}

// HasTvQuotaDays returns a boolean if a field has been set.
func (o *UserSettings) HasTvQuotaDays() bool {
	if o != nil && o.TvQuotaDays.IsSet() {
		return true
	}

	return false
}

// SetTvQuotaDays gets a reference to the given NullableFloat32 and assigns it to the TvQuotaDays field.
func (o *UserSettings) SetTvQuotaDays(v float32) {
	o.TvQuotaDays.Set(&v)
}
// SetTvQuotaDaysNil sets the value for TvQuotaDays to be an explicit nil
func (o *UserSettings) SetTvQuotaDaysNil() {
	o.TvQuotaDays.Set(nil)
}

// UnsetTvQuotaDays ensures that no value is present for TvQuotaDays, not even an explicit nil
func (o *UserSettings) UnsetTvQuotaDays() {
	o.TvQuotaDays.Unset()
}

// GetGlobalMovieQuotaDays returns the GlobalMovieQuotaDays field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserSettings) GetGlobalMovieQuotaDays() float32 {
	if o == nil || IsNil(o.GlobalMovieQuotaDays.Get()) {
		var ret float32
		return ret
	}
	return *o.GlobalMovieQuotaDays.Get()
}

// GetGlobalMovieQuotaDaysOk returns a tuple with the GlobalMovieQuotaDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserSettings) GetGlobalMovieQuotaDaysOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.GlobalMovieQuotaDays.Get(), o.GlobalMovieQuotaDays.IsSet()
}

// HasGlobalMovieQuotaDays returns a boolean if a field has been set.
func (o *UserSettings) HasGlobalMovieQuotaDays() bool {
	if o != nil && o.GlobalMovieQuotaDays.IsSet() {
		return true
	}

	return false
}

// SetGlobalMovieQuotaDays gets a reference to the given NullableFloat32 and assigns it to the GlobalMovieQuotaDays field.
func (o *UserSettings) SetGlobalMovieQuotaDays(v float32) {
	o.GlobalMovieQuotaDays.Set(&v)
}
// SetGlobalMovieQuotaDaysNil sets the value for GlobalMovieQuotaDays to be an explicit nil
func (o *UserSettings) SetGlobalMovieQuotaDaysNil() {
	o.GlobalMovieQuotaDays.Set(nil)
}

// UnsetGlobalMovieQuotaDays ensures that no value is present for GlobalMovieQuotaDays, not even an explicit nil
func (o *UserSettings) UnsetGlobalMovieQuotaDays() {
	o.GlobalMovieQuotaDays.Unset()
}

// GetGlobalMovieQuotaLimit returns the GlobalMovieQuotaLimit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserSettings) GetGlobalMovieQuotaLimit() float32 {
	if o == nil || IsNil(o.GlobalMovieQuotaLimit.Get()) {
		var ret float32
		return ret
	}
	return *o.GlobalMovieQuotaLimit.Get()
}

// GetGlobalMovieQuotaLimitOk returns a tuple with the GlobalMovieQuotaLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserSettings) GetGlobalMovieQuotaLimitOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.GlobalMovieQuotaLimit.Get(), o.GlobalMovieQuotaLimit.IsSet()
}

// HasGlobalMovieQuotaLimit returns a boolean if a field has been set.
func (o *UserSettings) HasGlobalMovieQuotaLimit() bool {
	if o != nil && o.GlobalMovieQuotaLimit.IsSet() {
		return true
	}

	return false
}

// SetGlobalMovieQuotaLimit gets a reference to the given NullableFloat32 and assigns it to the GlobalMovieQuotaLimit field.
func (o *UserSettings) SetGlobalMovieQuotaLimit(v float32) {
	o.GlobalMovieQuotaLimit.Set(&v)
}
// SetGlobalMovieQuotaLimitNil sets the value for GlobalMovieQuotaLimit to be an explicit nil
func (o *UserSettings) SetGlobalMovieQuotaLimitNil() {
	o.GlobalMovieQuotaLimit.Set(nil)
}

// UnsetGlobalMovieQuotaLimit ensures that no value is present for GlobalMovieQuotaLimit, not even an explicit nil
func (o *UserSettings) UnsetGlobalMovieQuotaLimit() {
	o.GlobalMovieQuotaLimit.Unset()
}

// GetGlobalTvQuotaLimit returns the GlobalTvQuotaLimit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserSettings) GetGlobalTvQuotaLimit() float32 {
	if o == nil || IsNil(o.GlobalTvQuotaLimit.Get()) {
		var ret float32
		return ret
	}
	return *o.GlobalTvQuotaLimit.Get()
}

// GetGlobalTvQuotaLimitOk returns a tuple with the GlobalTvQuotaLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserSettings) GetGlobalTvQuotaLimitOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.GlobalTvQuotaLimit.Get(), o.GlobalTvQuotaLimit.IsSet()
}

// HasGlobalTvQuotaLimit returns a boolean if a field has been set.
func (o *UserSettings) HasGlobalTvQuotaLimit() bool {
	if o != nil && o.GlobalTvQuotaLimit.IsSet() {
		return true
	}

	return false
}

// SetGlobalTvQuotaLimit gets a reference to the given NullableFloat32 and assigns it to the GlobalTvQuotaLimit field.
func (o *UserSettings) SetGlobalTvQuotaLimit(v float32) {
	o.GlobalTvQuotaLimit.Set(&v)
}
// SetGlobalTvQuotaLimitNil sets the value for GlobalTvQuotaLimit to be an explicit nil
func (o *UserSettings) SetGlobalTvQuotaLimitNil() {
	o.GlobalTvQuotaLimit.Set(nil)
}

// UnsetGlobalTvQuotaLimit ensures that no value is present for GlobalTvQuotaLimit, not even an explicit nil
func (o *UserSettings) UnsetGlobalTvQuotaLimit() {
	o.GlobalTvQuotaLimit.Unset()
}

// GetGlobalTvQuotaDays returns the GlobalTvQuotaDays field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserSettings) GetGlobalTvQuotaDays() float32 {
	if o == nil || IsNil(o.GlobalTvQuotaDays.Get()) {
		var ret float32
		return ret
	}
	return *o.GlobalTvQuotaDays.Get()
}

// GetGlobalTvQuotaDaysOk returns a tuple with the GlobalTvQuotaDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserSettings) GetGlobalTvQuotaDaysOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.GlobalTvQuotaDays.Get(), o.GlobalTvQuotaDays.IsSet()
}

// HasGlobalTvQuotaDays returns a boolean if a field has been set.
func (o *UserSettings) HasGlobalTvQuotaDays() bool {
	if o != nil && o.GlobalTvQuotaDays.IsSet() {
		return true
	}

	return false
}

// SetGlobalTvQuotaDays gets a reference to the given NullableFloat32 and assigns it to the GlobalTvQuotaDays field.
func (o *UserSettings) SetGlobalTvQuotaDays(v float32) {
	o.GlobalTvQuotaDays.Set(&v)
}
// SetGlobalTvQuotaDaysNil sets the value for GlobalTvQuotaDays to be an explicit nil
func (o *UserSettings) SetGlobalTvQuotaDaysNil() {
	o.GlobalTvQuotaDays.Set(nil)
}

// UnsetGlobalTvQuotaDays ensures that no value is present for GlobalTvQuotaDays, not even an explicit nil
func (o *UserSettings) UnsetGlobalTvQuotaDays() {
	o.GlobalTvQuotaDays.Unset()
}

// GetWatchlistSyncMovies returns the WatchlistSyncMovies field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserSettings) GetWatchlistSyncMovies() bool {
	if o == nil || IsNil(o.WatchlistSyncMovies.Get()) {
		var ret bool
		return ret
	}
	return *o.WatchlistSyncMovies.Get()
}

// GetWatchlistSyncMoviesOk returns a tuple with the WatchlistSyncMovies field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserSettings) GetWatchlistSyncMoviesOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.WatchlistSyncMovies.Get(), o.WatchlistSyncMovies.IsSet()
}

// HasWatchlistSyncMovies returns a boolean if a field has been set.
func (o *UserSettings) HasWatchlistSyncMovies() bool {
	if o != nil && o.WatchlistSyncMovies.IsSet() {
		return true
	}

	return false
}

// SetWatchlistSyncMovies gets a reference to the given NullableBool and assigns it to the WatchlistSyncMovies field.
func (o *UserSettings) SetWatchlistSyncMovies(v bool) {
	o.WatchlistSyncMovies.Set(&v)
}
// SetWatchlistSyncMoviesNil sets the value for WatchlistSyncMovies to be an explicit nil
func (o *UserSettings) SetWatchlistSyncMoviesNil() {
	o.WatchlistSyncMovies.Set(nil)
}

// UnsetWatchlistSyncMovies ensures that no value is present for WatchlistSyncMovies, not even an explicit nil
func (o *UserSettings) UnsetWatchlistSyncMovies() {
	o.WatchlistSyncMovies.Unset()
}

// GetWatchlistSyncTv returns the WatchlistSyncTv field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserSettings) GetWatchlistSyncTv() bool {
	if o == nil || IsNil(o.WatchlistSyncTv.Get()) {
		var ret bool
		return ret
	}
	return *o.WatchlistSyncTv.Get()
}

// GetWatchlistSyncTvOk returns a tuple with the WatchlistSyncTv field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserSettings) GetWatchlistSyncTvOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.WatchlistSyncTv.Get(), o.WatchlistSyncTv.IsSet()
}

// HasWatchlistSyncTv returns a boolean if a field has been set.
func (o *UserSettings) HasWatchlistSyncTv() bool {
	if o != nil && o.WatchlistSyncTv.IsSet() {
		return true
	}

	return false
}

// SetWatchlistSyncTv gets a reference to the given NullableBool and assigns it to the WatchlistSyncTv field.
func (o *UserSettings) SetWatchlistSyncTv(v bool) {
	o.WatchlistSyncTv.Set(&v)
}
// SetWatchlistSyncTvNil sets the value for WatchlistSyncTv to be an explicit nil
func (o *UserSettings) SetWatchlistSyncTvNil() {
	o.WatchlistSyncTv.Set(nil)
}

// UnsetWatchlistSyncTv ensures that no value is present for WatchlistSyncTv, not even an explicit nil
func (o *UserSettings) UnsetWatchlistSyncTv() {
	o.WatchlistSyncTv.Unset()
}

func (o UserSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Username.IsSet() {
		toSerialize["username"] = o.Username.Get()
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if o.DiscordId.IsSet() {
		toSerialize["discordId"] = o.DiscordId.Get()
	}
	if o.Locale.IsSet() {
		toSerialize["locale"] = o.Locale.Get()
	}
	if o.DiscoverRegion.IsSet() {
		toSerialize["discoverRegion"] = o.DiscoverRegion.Get()
	}
	if o.StreamingRegion.IsSet() {
		toSerialize["streamingRegion"] = o.StreamingRegion.Get()
	}
	if o.OriginalLanguage.IsSet() {
		toSerialize["originalLanguage"] = o.OriginalLanguage.Get()
	}
	if o.MovieQuotaLimit.IsSet() {
		toSerialize["movieQuotaLimit"] = o.MovieQuotaLimit.Get()
	}
	if o.MovieQuotaDays.IsSet() {
		toSerialize["movieQuotaDays"] = o.MovieQuotaDays.Get()
	}
	if o.TvQuotaLimit.IsSet() {
		toSerialize["tvQuotaLimit"] = o.TvQuotaLimit.Get()
	}
	if o.TvQuotaDays.IsSet() {
		toSerialize["tvQuotaDays"] = o.TvQuotaDays.Get()
	}
	if o.GlobalMovieQuotaDays.IsSet() {
		toSerialize["globalMovieQuotaDays"] = o.GlobalMovieQuotaDays.Get()
	}
	if o.GlobalMovieQuotaLimit.IsSet() {
		toSerialize["globalMovieQuotaLimit"] = o.GlobalMovieQuotaLimit.Get()
	}
	if o.GlobalTvQuotaLimit.IsSet() {
		toSerialize["globalTvQuotaLimit"] = o.GlobalTvQuotaLimit.Get()
	}
	if o.GlobalTvQuotaDays.IsSet() {
		toSerialize["globalTvQuotaDays"] = o.GlobalTvQuotaDays.Get()
	}
	if o.WatchlistSyncMovies.IsSet() {
		toSerialize["watchlistSyncMovies"] = o.WatchlistSyncMovies.Get()
	}
	if o.WatchlistSyncTv.IsSet() {
		toSerialize["watchlistSyncTv"] = o.WatchlistSyncTv.Get()
	}
	return toSerialize, nil
}

type NullableUserSettings struct {
	value *UserSettings
	isSet bool
}

func (v NullableUserSettings) Get() *UserSettings {
	return v.value
}

func (v *NullableUserSettings) Set(val *UserSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableUserSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableUserSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserSettings(val *UserSettings) *NullableUserSettings {
	return &NullableUserSettings{value: val, isSet: true}
}

func (v NullableUserSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


