/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the NetworkSettingsProxy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkSettingsProxy{}

// NetworkSettingsProxy struct for NetworkSettingsProxy
type NetworkSettingsProxy struct {
	Enabled *bool `json:"enabled,omitempty"`
	Hostname *string `json:"hostname,omitempty"`
	Port *float32 `json:"port,omitempty"`
	UseSsl *bool `json:"useSsl,omitempty"`
	User *string `json:"user,omitempty"`
	Password *string `json:"password,omitempty"`
	BypassFilter *string `json:"bypassFilter,omitempty"`
	BypassLocalAddresses *bool `json:"bypassLocalAddresses,omitempty"`
}

// NewNetworkSettingsProxy instantiates a new NetworkSettingsProxy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkSettingsProxy() *NetworkSettingsProxy {
	this := NetworkSettingsProxy{}
	return &this
}

// NewNetworkSettingsProxyWithDefaults instantiates a new NetworkSettingsProxy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkSettingsProxyWithDefaults() *NetworkSettingsProxy {
	this := NetworkSettingsProxy{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *NetworkSettingsProxy) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkSettingsProxy) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *NetworkSettingsProxy) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *NetworkSettingsProxy) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetHostname returns the Hostname field value if set, zero value otherwise.
func (o *NetworkSettingsProxy) GetHostname() string {
	if o == nil || IsNil(o.Hostname) {
		var ret string
		return ret
	}
	return *o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkSettingsProxy) GetHostnameOk() (*string, bool) {
	if o == nil || IsNil(o.Hostname) {
		return nil, false
	}
	return o.Hostname, true
}

// HasHostname returns a boolean if a field has been set.
func (o *NetworkSettingsProxy) HasHostname() bool {
	if o != nil && !IsNil(o.Hostname) {
		return true
	}

	return false
}

// SetHostname gets a reference to the given string and assigns it to the Hostname field.
func (o *NetworkSettingsProxy) SetHostname(v string) {
	o.Hostname = &v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *NetworkSettingsProxy) GetPort() float32 {
	if o == nil || IsNil(o.Port) {
		var ret float32
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkSettingsProxy) GetPortOk() (*float32, bool) {
	if o == nil || IsNil(o.Port) {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *NetworkSettingsProxy) HasPort() bool {
	if o != nil && !IsNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given float32 and assigns it to the Port field.
func (o *NetworkSettingsProxy) SetPort(v float32) {
	o.Port = &v
}

// GetUseSsl returns the UseSsl field value if set, zero value otherwise.
func (o *NetworkSettingsProxy) GetUseSsl() bool {
	if o == nil || IsNil(o.UseSsl) {
		var ret bool
		return ret
	}
	return *o.UseSsl
}

// GetUseSslOk returns a tuple with the UseSsl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkSettingsProxy) GetUseSslOk() (*bool, bool) {
	if o == nil || IsNil(o.UseSsl) {
		return nil, false
	}
	return o.UseSsl, true
}

// HasUseSsl returns a boolean if a field has been set.
func (o *NetworkSettingsProxy) HasUseSsl() bool {
	if o != nil && !IsNil(o.UseSsl) {
		return true
	}

	return false
}

// SetUseSsl gets a reference to the given bool and assigns it to the UseSsl field.
func (o *NetworkSettingsProxy) SetUseSsl(v bool) {
	o.UseSsl = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *NetworkSettingsProxy) GetUser() string {
	if o == nil || IsNil(o.User) {
		var ret string
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkSettingsProxy) GetUserOk() (*string, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *NetworkSettingsProxy) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given string and assigns it to the User field.
func (o *NetworkSettingsProxy) SetUser(v string) {
	o.User = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *NetworkSettingsProxy) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkSettingsProxy) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *NetworkSettingsProxy) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *NetworkSettingsProxy) SetPassword(v string) {
	o.Password = &v
}

// GetBypassFilter returns the BypassFilter field value if set, zero value otherwise.
func (o *NetworkSettingsProxy) GetBypassFilter() string {
	if o == nil || IsNil(o.BypassFilter) {
		var ret string
		return ret
	}
	return *o.BypassFilter
}

// GetBypassFilterOk returns a tuple with the BypassFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkSettingsProxy) GetBypassFilterOk() (*string, bool) {
	if o == nil || IsNil(o.BypassFilter) {
		return nil, false
	}
	return o.BypassFilter, true
}

// HasBypassFilter returns a boolean if a field has been set.
func (o *NetworkSettingsProxy) HasBypassFilter() bool {
	if o != nil && !IsNil(o.BypassFilter) {
		return true
	}

	return false
}

// SetBypassFilter gets a reference to the given string and assigns it to the BypassFilter field.
func (o *NetworkSettingsProxy) SetBypassFilter(v string) {
	o.BypassFilter = &v
}

// GetBypassLocalAddresses returns the BypassLocalAddresses field value if set, zero value otherwise.
func (o *NetworkSettingsProxy) GetBypassLocalAddresses() bool {
	if o == nil || IsNil(o.BypassLocalAddresses) {
		var ret bool
		return ret
	}
	return *o.BypassLocalAddresses
}

// GetBypassLocalAddressesOk returns a tuple with the BypassLocalAddresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkSettingsProxy) GetBypassLocalAddressesOk() (*bool, bool) {
	if o == nil || IsNil(o.BypassLocalAddresses) {
		return nil, false
	}
	return o.BypassLocalAddresses, true
}

// HasBypassLocalAddresses returns a boolean if a field has been set.
func (o *NetworkSettingsProxy) HasBypassLocalAddresses() bool {
	if o != nil && !IsNil(o.BypassLocalAddresses) {
		return true
	}

	return false
}

// SetBypassLocalAddresses gets a reference to the given bool and assigns it to the BypassLocalAddresses field.
func (o *NetworkSettingsProxy) SetBypassLocalAddresses(v bool) {
	o.BypassLocalAddresses = &v
}

func (o NetworkSettingsProxy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkSettingsProxy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Hostname) {
		toSerialize["hostname"] = o.Hostname
	}
	if !IsNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	if !IsNil(o.UseSsl) {
		toSerialize["useSsl"] = o.UseSsl
	}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.BypassFilter) {
		toSerialize["bypassFilter"] = o.BypassFilter
	}
	if !IsNil(o.BypassLocalAddresses) {
		toSerialize["bypassLocalAddresses"] = o.BypassLocalAddresses
	}
	return toSerialize, nil
}

type NullableNetworkSettingsProxy struct {
	value *NetworkSettingsProxy
	isSet bool
}

func (v NullableNetworkSettingsProxy) Get() *NetworkSettingsProxy {
	return v.value
}

func (v *NullableNetworkSettingsProxy) Set(val *NetworkSettingsProxy) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkSettingsProxy) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkSettingsProxy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkSettingsProxy(val *NetworkSettingsProxy) *NullableNetworkSettingsProxy {
	return &NullableNetworkSettingsProxy{value: val, isSet: true}
}

func (v NullableNetworkSettingsProxy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkSettingsProxy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


