/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the CertificationsMovieGet500Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CertificationsMovieGet500Response{}

// CertificationsMovieGet500Response struct for CertificationsMovieGet500Response
type CertificationsMovieGet500Response struct {
	Status *float32 `json:"status,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewCertificationsMovieGet500Response instantiates a new CertificationsMovieGet500Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCertificationsMovieGet500Response() *CertificationsMovieGet500Response {
	this := CertificationsMovieGet500Response{}
	return &this
}

// NewCertificationsMovieGet500ResponseWithDefaults instantiates a new CertificationsMovieGet500Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCertificationsMovieGet500ResponseWithDefaults() *CertificationsMovieGet500Response {
	this := CertificationsMovieGet500Response{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CertificationsMovieGet500Response) GetStatus() float32 {
	if o == nil || IsNil(o.Status) {
		var ret float32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificationsMovieGet500Response) GetStatusOk() (*float32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CertificationsMovieGet500Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given float32 and assigns it to the Status field.
func (o *CertificationsMovieGet500Response) SetStatus(v float32) {
	o.Status = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CertificationsMovieGet500Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificationsMovieGet500Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CertificationsMovieGet500Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CertificationsMovieGet500Response) SetMessage(v string) {
	o.Message = &v
}

func (o CertificationsMovieGet500Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CertificationsMovieGet500Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableCertificationsMovieGet500Response struct {
	value *CertificationsMovieGet500Response
	isSet bool
}

func (v NullableCertificationsMovieGet500Response) Get() *CertificationsMovieGet500Response {
	return v.value
}

func (v *NullableCertificationsMovieGet500Response) Set(val *CertificationsMovieGet500Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCertificationsMovieGet500Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCertificationsMovieGet500Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertificationsMovieGet500Response(val *CertificationsMovieGet500Response) *NullableCertificationsMovieGet500Response {
	return &NullableCertificationsMovieGet500Response{value: val, isSet: true}
}

func (v NullableCertificationsMovieGet500Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertificationsMovieGet500Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


