/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the UserUserIdPushSubscriptionsGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserUserIdPushSubscriptionsGet200Response{}

// UserUserIdPushSubscriptionsGet200Response struct for UserUserIdPushSubscriptionsGet200Response
type UserUserIdPushSubscriptionsGet200Response struct {
	Endpoint *string `json:"endpoint,omitempty"`
	P256dh *string `json:"p256dh,omitempty"`
	Auth *string `json:"auth,omitempty"`
	UserAgent *string `json:"userAgent,omitempty"`
}

// NewUserUserIdPushSubscriptionsGet200Response instantiates a new UserUserIdPushSubscriptionsGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserUserIdPushSubscriptionsGet200Response() *UserUserIdPushSubscriptionsGet200Response {
	this := UserUserIdPushSubscriptionsGet200Response{}
	return &this
}

// NewUserUserIdPushSubscriptionsGet200ResponseWithDefaults instantiates a new UserUserIdPushSubscriptionsGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserUserIdPushSubscriptionsGet200ResponseWithDefaults() *UserUserIdPushSubscriptionsGet200Response {
	this := UserUserIdPushSubscriptionsGet200Response{}
	return &this
}

// GetEndpoint returns the Endpoint field value if set, zero value otherwise.
func (o *UserUserIdPushSubscriptionsGet200Response) GetEndpoint() string {
	if o == nil || IsNil(o.Endpoint) {
		var ret string
		return ret
	}
	return *o.Endpoint
}

// GetEndpointOk returns a tuple with the Endpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserUserIdPushSubscriptionsGet200Response) GetEndpointOk() (*string, bool) {
	if o == nil || IsNil(o.Endpoint) {
		return nil, false
	}
	return o.Endpoint, true
}

// HasEndpoint returns a boolean if a field has been set.
func (o *UserUserIdPushSubscriptionsGet200Response) HasEndpoint() bool {
	if o != nil && !IsNil(o.Endpoint) {
		return true
	}

	return false
}

// SetEndpoint gets a reference to the given string and assigns it to the Endpoint field.
func (o *UserUserIdPushSubscriptionsGet200Response) SetEndpoint(v string) {
	o.Endpoint = &v
}

// GetP256dh returns the P256dh field value if set, zero value otherwise.
func (o *UserUserIdPushSubscriptionsGet200Response) GetP256dh() string {
	if o == nil || IsNil(o.P256dh) {
		var ret string
		return ret
	}
	return *o.P256dh
}

// GetP256dhOk returns a tuple with the P256dh field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserUserIdPushSubscriptionsGet200Response) GetP256dhOk() (*string, bool) {
	if o == nil || IsNil(o.P256dh) {
		return nil, false
	}
	return o.P256dh, true
}

// HasP256dh returns a boolean if a field has been set.
func (o *UserUserIdPushSubscriptionsGet200Response) HasP256dh() bool {
	if o != nil && !IsNil(o.P256dh) {
		return true
	}

	return false
}

// SetP256dh gets a reference to the given string and assigns it to the P256dh field.
func (o *UserUserIdPushSubscriptionsGet200Response) SetP256dh(v string) {
	o.P256dh = &v
}

// GetAuth returns the Auth field value if set, zero value otherwise.
func (o *UserUserIdPushSubscriptionsGet200Response) GetAuth() string {
	if o == nil || IsNil(o.Auth) {
		var ret string
		return ret
	}
	return *o.Auth
}

// GetAuthOk returns a tuple with the Auth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserUserIdPushSubscriptionsGet200Response) GetAuthOk() (*string, bool) {
	if o == nil || IsNil(o.Auth) {
		return nil, false
	}
	return o.Auth, true
}

// HasAuth returns a boolean if a field has been set.
func (o *UserUserIdPushSubscriptionsGet200Response) HasAuth() bool {
	if o != nil && !IsNil(o.Auth) {
		return true
	}

	return false
}

// SetAuth gets a reference to the given string and assigns it to the Auth field.
func (o *UserUserIdPushSubscriptionsGet200Response) SetAuth(v string) {
	o.Auth = &v
}

// GetUserAgent returns the UserAgent field value if set, zero value otherwise.
func (o *UserUserIdPushSubscriptionsGet200Response) GetUserAgent() string {
	if o == nil || IsNil(o.UserAgent) {
		var ret string
		return ret
	}
	return *o.UserAgent
}

// GetUserAgentOk returns a tuple with the UserAgent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserUserIdPushSubscriptionsGet200Response) GetUserAgentOk() (*string, bool) {
	if o == nil || IsNil(o.UserAgent) {
		return nil, false
	}
	return o.UserAgent, true
}

// HasUserAgent returns a boolean if a field has been set.
func (o *UserUserIdPushSubscriptionsGet200Response) HasUserAgent() bool {
	if o != nil && !IsNil(o.UserAgent) {
		return true
	}

	return false
}

// SetUserAgent gets a reference to the given string and assigns it to the UserAgent field.
func (o *UserUserIdPushSubscriptionsGet200Response) SetUserAgent(v string) {
	o.UserAgent = &v
}

func (o UserUserIdPushSubscriptionsGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserUserIdPushSubscriptionsGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Endpoint) {
		toSerialize["endpoint"] = o.Endpoint
	}
	if !IsNil(o.P256dh) {
		toSerialize["p256dh"] = o.P256dh
	}
	if !IsNil(o.Auth) {
		toSerialize["auth"] = o.Auth
	}
	if !IsNil(o.UserAgent) {
		toSerialize["userAgent"] = o.UserAgent
	}
	return toSerialize, nil
}

type NullableUserUserIdPushSubscriptionsGet200Response struct {
	value *UserUserIdPushSubscriptionsGet200Response
	isSet bool
}

func (v NullableUserUserIdPushSubscriptionsGet200Response) Get() *UserUserIdPushSubscriptionsGet200Response {
	return v.value
}

func (v *NullableUserUserIdPushSubscriptionsGet200Response) Set(val *UserUserIdPushSubscriptionsGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUserUserIdPushSubscriptionsGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUserUserIdPushSubscriptionsGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserUserIdPushSubscriptionsGet200Response(val *UserUserIdPushSubscriptionsGet200Response) *NullableUserUserIdPushSubscriptionsGet200Response {
	return &NullableUserUserIdPushSubscriptionsGet200Response{value: val, isSet: true}
}

func (v NullableUserUserIdPushSubscriptionsGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserUserIdPushSubscriptionsGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


