/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the SettingsCacheGet200ResponseDnsCacheEntriesValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SettingsCacheGet200ResponseDnsCacheEntriesValue{}

// SettingsCacheGet200ResponseDnsCacheEntriesValue struct for SettingsCacheGet200ResponseDnsCacheEntriesValue
type SettingsCacheGet200ResponseDnsCacheEntriesValue struct {
	Addresses *SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses `json:"addresses,omitempty"`
	ActiveAddress *string `json:"activeAddress,omitempty"`
	Family *float32 `json:"family,omitempty"`
	Age *float32 `json:"age,omitempty"`
	Ttl *float32 `json:"ttl,omitempty"`
	NetworkErrors *float32 `json:"networkErrors,omitempty"`
	Hits *float32 `json:"hits,omitempty"`
	Misses *float32 `json:"misses,omitempty"`
}

// NewSettingsCacheGet200ResponseDnsCacheEntriesValue instantiates a new SettingsCacheGet200ResponseDnsCacheEntriesValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSettingsCacheGet200ResponseDnsCacheEntriesValue() *SettingsCacheGet200ResponseDnsCacheEntriesValue {
	this := SettingsCacheGet200ResponseDnsCacheEntriesValue{}
	return &this
}

// NewSettingsCacheGet200ResponseDnsCacheEntriesValueWithDefaults instantiates a new SettingsCacheGet200ResponseDnsCacheEntriesValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSettingsCacheGet200ResponseDnsCacheEntriesValueWithDefaults() *SettingsCacheGet200ResponseDnsCacheEntriesValue {
	this := SettingsCacheGet200ResponseDnsCacheEntriesValue{}
	return &this
}

// GetAddresses returns the Addresses field value if set, zero value otherwise.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) GetAddresses() SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses {
	if o == nil || IsNil(o.Addresses) {
		var ret SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses
		return ret
	}
	return *o.Addresses
}

// GetAddressesOk returns a tuple with the Addresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) GetAddressesOk() (*SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses, bool) {
	if o == nil || IsNil(o.Addresses) {
		return nil, false
	}
	return o.Addresses, true
}

// HasAddresses returns a boolean if a field has been set.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) HasAddresses() bool {
	if o != nil && !IsNil(o.Addresses) {
		return true
	}

	return false
}

// SetAddresses gets a reference to the given SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses and assigns it to the Addresses field.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) SetAddresses(v SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses) {
	o.Addresses = &v
}

// GetActiveAddress returns the ActiveAddress field value if set, zero value otherwise.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) GetActiveAddress() string {
	if o == nil || IsNil(o.ActiveAddress) {
		var ret string
		return ret
	}
	return *o.ActiveAddress
}

// GetActiveAddressOk returns a tuple with the ActiveAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) GetActiveAddressOk() (*string, bool) {
	if o == nil || IsNil(o.ActiveAddress) {
		return nil, false
	}
	return o.ActiveAddress, true
}

// HasActiveAddress returns a boolean if a field has been set.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) HasActiveAddress() bool {
	if o != nil && !IsNil(o.ActiveAddress) {
		return true
	}

	return false
}

// SetActiveAddress gets a reference to the given string and assigns it to the ActiveAddress field.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) SetActiveAddress(v string) {
	o.ActiveAddress = &v
}

// GetFamily returns the Family field value if set, zero value otherwise.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) GetFamily() float32 {
	if o == nil || IsNil(o.Family) {
		var ret float32
		return ret
	}
	return *o.Family
}

// GetFamilyOk returns a tuple with the Family field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) GetFamilyOk() (*float32, bool) {
	if o == nil || IsNil(o.Family) {
		return nil, false
	}
	return o.Family, true
}

// HasFamily returns a boolean if a field has been set.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) HasFamily() bool {
	if o != nil && !IsNil(o.Family) {
		return true
	}

	return false
}

// SetFamily gets a reference to the given float32 and assigns it to the Family field.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) SetFamily(v float32) {
	o.Family = &v
}

// GetAge returns the Age field value if set, zero value otherwise.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) GetAge() float32 {
	if o == nil || IsNil(o.Age) {
		var ret float32
		return ret
	}
	return *o.Age
}

// GetAgeOk returns a tuple with the Age field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) GetAgeOk() (*float32, bool) {
	if o == nil || IsNil(o.Age) {
		return nil, false
	}
	return o.Age, true
}

// HasAge returns a boolean if a field has been set.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) HasAge() bool {
	if o != nil && !IsNil(o.Age) {
		return true
	}

	return false
}

// SetAge gets a reference to the given float32 and assigns it to the Age field.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) SetAge(v float32) {
	o.Age = &v
}

// GetTtl returns the Ttl field value if set, zero value otherwise.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) GetTtl() float32 {
	if o == nil || IsNil(o.Ttl) {
		var ret float32
		return ret
	}
	return *o.Ttl
}

// GetTtlOk returns a tuple with the Ttl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) GetTtlOk() (*float32, bool) {
	if o == nil || IsNil(o.Ttl) {
		return nil, false
	}
	return o.Ttl, true
}

// HasTtl returns a boolean if a field has been set.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) HasTtl() bool {
	if o != nil && !IsNil(o.Ttl) {
		return true
	}

	return false
}

// SetTtl gets a reference to the given float32 and assigns it to the Ttl field.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) SetTtl(v float32) {
	o.Ttl = &v
}

// GetNetworkErrors returns the NetworkErrors field value if set, zero value otherwise.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) GetNetworkErrors() float32 {
	if o == nil || IsNil(o.NetworkErrors) {
		var ret float32
		return ret
	}
	return *o.NetworkErrors
}

// GetNetworkErrorsOk returns a tuple with the NetworkErrors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) GetNetworkErrorsOk() (*float32, bool) {
	if o == nil || IsNil(o.NetworkErrors) {
		return nil, false
	}
	return o.NetworkErrors, true
}

// HasNetworkErrors returns a boolean if a field has been set.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) HasNetworkErrors() bool {
	if o != nil && !IsNil(o.NetworkErrors) {
		return true
	}

	return false
}

// SetNetworkErrors gets a reference to the given float32 and assigns it to the NetworkErrors field.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) SetNetworkErrors(v float32) {
	o.NetworkErrors = &v
}

// GetHits returns the Hits field value if set, zero value otherwise.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) GetHits() float32 {
	if o == nil || IsNil(o.Hits) {
		var ret float32
		return ret
	}
	return *o.Hits
}

// GetHitsOk returns a tuple with the Hits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) GetHitsOk() (*float32, bool) {
	if o == nil || IsNil(o.Hits) {
		return nil, false
	}
	return o.Hits, true
}

// HasHits returns a boolean if a field has been set.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) HasHits() bool {
	if o != nil && !IsNil(o.Hits) {
		return true
	}

	return false
}

// SetHits gets a reference to the given float32 and assigns it to the Hits field.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) SetHits(v float32) {
	o.Hits = &v
}

// GetMisses returns the Misses field value if set, zero value otherwise.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) GetMisses() float32 {
	if o == nil || IsNil(o.Misses) {
		var ret float32
		return ret
	}
	return *o.Misses
}

// GetMissesOk returns a tuple with the Misses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) GetMissesOk() (*float32, bool) {
	if o == nil || IsNil(o.Misses) {
		return nil, false
	}
	return o.Misses, true
}

// HasMisses returns a boolean if a field has been set.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) HasMisses() bool {
	if o != nil && !IsNil(o.Misses) {
		return true
	}

	return false
}

// SetMisses gets a reference to the given float32 and assigns it to the Misses field.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValue) SetMisses(v float32) {
	o.Misses = &v
}

func (o SettingsCacheGet200ResponseDnsCacheEntriesValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SettingsCacheGet200ResponseDnsCacheEntriesValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Addresses) {
		toSerialize["addresses"] = o.Addresses
	}
	if !IsNil(o.ActiveAddress) {
		toSerialize["activeAddress"] = o.ActiveAddress
	}
	if !IsNil(o.Family) {
		toSerialize["family"] = o.Family
	}
	if !IsNil(o.Age) {
		toSerialize["age"] = o.Age
	}
	if !IsNil(o.Ttl) {
		toSerialize["ttl"] = o.Ttl
	}
	if !IsNil(o.NetworkErrors) {
		toSerialize["networkErrors"] = o.NetworkErrors
	}
	if !IsNil(o.Hits) {
		toSerialize["hits"] = o.Hits
	}
	if !IsNil(o.Misses) {
		toSerialize["misses"] = o.Misses
	}
	return toSerialize, nil
}

type NullableSettingsCacheGet200ResponseDnsCacheEntriesValue struct {
	value *SettingsCacheGet200ResponseDnsCacheEntriesValue
	isSet bool
}

func (v NullableSettingsCacheGet200ResponseDnsCacheEntriesValue) Get() *SettingsCacheGet200ResponseDnsCacheEntriesValue {
	return v.value
}

func (v *NullableSettingsCacheGet200ResponseDnsCacheEntriesValue) Set(val *SettingsCacheGet200ResponseDnsCacheEntriesValue) {
	v.value = val
	v.isSet = true
}

func (v NullableSettingsCacheGet200ResponseDnsCacheEntriesValue) IsSet() bool {
	return v.isSet
}

func (v *NullableSettingsCacheGet200ResponseDnsCacheEntriesValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSettingsCacheGet200ResponseDnsCacheEntriesValue(val *SettingsCacheGet200ResponseDnsCacheEntriesValue) *NullableSettingsCacheGet200ResponseDnsCacheEntriesValue {
	return &NullableSettingsCacheGet200ResponseDnsCacheEntriesValue{value: val, isSet: true}
}

func (v NullableSettingsCacheGet200ResponseDnsCacheEntriesValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSettingsCacheGet200ResponseDnsCacheEntriesValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


