/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the UserUserIdSettingsLinkedAccountsJellyfinPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserUserIdSettingsLinkedAccountsJellyfinPostRequest{}

// UserUserIdSettingsLinkedAccountsJellyfinPostRequest struct for UserUserIdSettingsLinkedAccountsJellyfinPostRequest
type UserUserIdSettingsLinkedAccountsJellyfinPostRequest struct {
	Username *string `json:"username,omitempty"`
	Password *string `json:"password,omitempty"`
}

// NewUserUserIdSettingsLinkedAccountsJellyfinPostRequest instantiates a new UserUserIdSettingsLinkedAccountsJellyfinPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserUserIdSettingsLinkedAccountsJellyfinPostRequest() *UserUserIdSettingsLinkedAccountsJellyfinPostRequest {
	this := UserUserIdSettingsLinkedAccountsJellyfinPostRequest{}
	return &this
}

// NewUserUserIdSettingsLinkedAccountsJellyfinPostRequestWithDefaults instantiates a new UserUserIdSettingsLinkedAccountsJellyfinPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserUserIdSettingsLinkedAccountsJellyfinPostRequestWithDefaults() *UserUserIdSettingsLinkedAccountsJellyfinPostRequest {
	this := UserUserIdSettingsLinkedAccountsJellyfinPostRequest{}
	return &this
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *UserUserIdSettingsLinkedAccountsJellyfinPostRequest) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserUserIdSettingsLinkedAccountsJellyfinPostRequest) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *UserUserIdSettingsLinkedAccountsJellyfinPostRequest) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *UserUserIdSettingsLinkedAccountsJellyfinPostRequest) SetUsername(v string) {
	o.Username = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *UserUserIdSettingsLinkedAccountsJellyfinPostRequest) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserUserIdSettingsLinkedAccountsJellyfinPostRequest) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *UserUserIdSettingsLinkedAccountsJellyfinPostRequest) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *UserUserIdSettingsLinkedAccountsJellyfinPostRequest) SetPassword(v string) {
	o.Password = &v
}

func (o UserUserIdSettingsLinkedAccountsJellyfinPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserUserIdSettingsLinkedAccountsJellyfinPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	return toSerialize, nil
}

type NullableUserUserIdSettingsLinkedAccountsJellyfinPostRequest struct {
	value *UserUserIdSettingsLinkedAccountsJellyfinPostRequest
	isSet bool
}

func (v NullableUserUserIdSettingsLinkedAccountsJellyfinPostRequest) Get() *UserUserIdSettingsLinkedAccountsJellyfinPostRequest {
	return v.value
}

func (v *NullableUserUserIdSettingsLinkedAccountsJellyfinPostRequest) Set(val *UserUserIdSettingsLinkedAccountsJellyfinPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUserUserIdSettingsLinkedAccountsJellyfinPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUserUserIdSettingsLinkedAccountsJellyfinPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserUserIdSettingsLinkedAccountsJellyfinPostRequest(val *UserUserIdSettingsLinkedAccountsJellyfinPostRequest) *NullableUserUserIdSettingsLinkedAccountsJellyfinPostRequest {
	return &NullableUserUserIdSettingsLinkedAccountsJellyfinPostRequest{value: val, isSet: true}
}

func (v NullableUserUserIdSettingsLinkedAccountsJellyfinPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserUserIdSettingsLinkedAccountsJellyfinPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


