/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the KeywordKeywordIdGet500Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KeywordKeywordIdGet500Response{}

// KeywordKeywordIdGet500Response struct for KeywordKeywordIdGet500Response
type KeywordKeywordIdGet500Response struct {
	Message *string `json:"message,omitempty"`
}

// NewKeywordKeywordIdGet500Response instantiates a new KeywordKeywordIdGet500Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKeywordKeywordIdGet500Response() *KeywordKeywordIdGet500Response {
	this := KeywordKeywordIdGet500Response{}
	return &this
}

// NewKeywordKeywordIdGet500ResponseWithDefaults instantiates a new KeywordKeywordIdGet500Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKeywordKeywordIdGet500ResponseWithDefaults() *KeywordKeywordIdGet500Response {
	this := KeywordKeywordIdGet500Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *KeywordKeywordIdGet500Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeywordKeywordIdGet500Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *KeywordKeywordIdGet500Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *KeywordKeywordIdGet500Response) SetMessage(v string) {
	o.Message = &v
}

func (o KeywordKeywordIdGet500Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KeywordKeywordIdGet500Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableKeywordKeywordIdGet500Response struct {
	value *KeywordKeywordIdGet500Response
	isSet bool
}

func (v NullableKeywordKeywordIdGet500Response) Get() *KeywordKeywordIdGet500Response {
	return v.value
}

func (v *NullableKeywordKeywordIdGet500Response) Set(val *KeywordKeywordIdGet500Response) {
	v.value = val
	v.isSet = true
}

func (v NullableKeywordKeywordIdGet500Response) IsSet() bool {
	return v.isSet
}

func (v *NullableKeywordKeywordIdGet500Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKeywordKeywordIdGet500Response(val *KeywordKeywordIdGet500Response) *NullableKeywordKeywordIdGet500Response {
	return &NullableKeywordKeywordIdGet500Response{value: val, isSet: true}
}

func (v NullableKeywordKeywordIdGet500Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKeywordKeywordIdGet500Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


