/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the NetworkSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkSettings{}

// NetworkSettings struct for NetworkSettings
type NetworkSettings struct {
	CsrfProtection *bool `json:"csrfProtection,omitempty"`
	ForceIpv4First *bool `json:"forceIpv4First,omitempty"`
	TrustProxy *bool `json:"trustProxy,omitempty"`
	Proxy *NetworkSettingsProxy `json:"proxy,omitempty"`
	DnsCache *NetworkSettingsDnsCache `json:"dnsCache,omitempty"`
}

// NewNetworkSettings instantiates a new NetworkSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkSettings() *NetworkSettings {
	this := NetworkSettings{}
	return &this
}

// NewNetworkSettingsWithDefaults instantiates a new NetworkSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkSettingsWithDefaults() *NetworkSettings {
	this := NetworkSettings{}
	return &this
}

// GetCsrfProtection returns the CsrfProtection field value if set, zero value otherwise.
func (o *NetworkSettings) GetCsrfProtection() bool {
	if o == nil || IsNil(o.CsrfProtection) {
		var ret bool
		return ret
	}
	return *o.CsrfProtection
}

// GetCsrfProtectionOk returns a tuple with the CsrfProtection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkSettings) GetCsrfProtectionOk() (*bool, bool) {
	if o == nil || IsNil(o.CsrfProtection) {
		return nil, false
	}
	return o.CsrfProtection, true
}

// HasCsrfProtection returns a boolean if a field has been set.
func (o *NetworkSettings) HasCsrfProtection() bool {
	if o != nil && !IsNil(o.CsrfProtection) {
		return true
	}

	return false
}

// SetCsrfProtection gets a reference to the given bool and assigns it to the CsrfProtection field.
func (o *NetworkSettings) SetCsrfProtection(v bool) {
	o.CsrfProtection = &v
}

// GetForceIpv4First returns the ForceIpv4First field value if set, zero value otherwise.
func (o *NetworkSettings) GetForceIpv4First() bool {
	if o == nil || IsNil(o.ForceIpv4First) {
		var ret bool
		return ret
	}
	return *o.ForceIpv4First
}

// GetForceIpv4FirstOk returns a tuple with the ForceIpv4First field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkSettings) GetForceIpv4FirstOk() (*bool, bool) {
	if o == nil || IsNil(o.ForceIpv4First) {
		return nil, false
	}
	return o.ForceIpv4First, true
}

// HasForceIpv4First returns a boolean if a field has been set.
func (o *NetworkSettings) HasForceIpv4First() bool {
	if o != nil && !IsNil(o.ForceIpv4First) {
		return true
	}

	return false
}

// SetForceIpv4First gets a reference to the given bool and assigns it to the ForceIpv4First field.
func (o *NetworkSettings) SetForceIpv4First(v bool) {
	o.ForceIpv4First = &v
}

// GetTrustProxy returns the TrustProxy field value if set, zero value otherwise.
func (o *NetworkSettings) GetTrustProxy() bool {
	if o == nil || IsNil(o.TrustProxy) {
		var ret bool
		return ret
	}
	return *o.TrustProxy
}

// GetTrustProxyOk returns a tuple with the TrustProxy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkSettings) GetTrustProxyOk() (*bool, bool) {
	if o == nil || IsNil(o.TrustProxy) {
		return nil, false
	}
	return o.TrustProxy, true
}

// HasTrustProxy returns a boolean if a field has been set.
func (o *NetworkSettings) HasTrustProxy() bool {
	if o != nil && !IsNil(o.TrustProxy) {
		return true
	}

	return false
}

// SetTrustProxy gets a reference to the given bool and assigns it to the TrustProxy field.
func (o *NetworkSettings) SetTrustProxy(v bool) {
	o.TrustProxy = &v
}

// GetProxy returns the Proxy field value if set, zero value otherwise.
func (o *NetworkSettings) GetProxy() NetworkSettingsProxy {
	if o == nil || IsNil(o.Proxy) {
		var ret NetworkSettingsProxy
		return ret
	}
	return *o.Proxy
}

// GetProxyOk returns a tuple with the Proxy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkSettings) GetProxyOk() (*NetworkSettingsProxy, bool) {
	if o == nil || IsNil(o.Proxy) {
		return nil, false
	}
	return o.Proxy, true
}

// HasProxy returns a boolean if a field has been set.
func (o *NetworkSettings) HasProxy() bool {
	if o != nil && !IsNil(o.Proxy) {
		return true
	}

	return false
}

// SetProxy gets a reference to the given NetworkSettingsProxy and assigns it to the Proxy field.
func (o *NetworkSettings) SetProxy(v NetworkSettingsProxy) {
	o.Proxy = &v
}

// GetDnsCache returns the DnsCache field value if set, zero value otherwise.
func (o *NetworkSettings) GetDnsCache() NetworkSettingsDnsCache {
	if o == nil || IsNil(o.DnsCache) {
		var ret NetworkSettingsDnsCache
		return ret
	}
	return *o.DnsCache
}

// GetDnsCacheOk returns a tuple with the DnsCache field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkSettings) GetDnsCacheOk() (*NetworkSettingsDnsCache, bool) {
	if o == nil || IsNil(o.DnsCache) {
		return nil, false
	}
	return o.DnsCache, true
}

// HasDnsCache returns a boolean if a field has been set.
func (o *NetworkSettings) HasDnsCache() bool {
	if o != nil && !IsNil(o.DnsCache) {
		return true
	}

	return false
}

// SetDnsCache gets a reference to the given NetworkSettingsDnsCache and assigns it to the DnsCache field.
func (o *NetworkSettings) SetDnsCache(v NetworkSettingsDnsCache) {
	o.DnsCache = &v
}

func (o NetworkSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CsrfProtection) {
		toSerialize["csrfProtection"] = o.CsrfProtection
	}
	if !IsNil(o.ForceIpv4First) {
		toSerialize["forceIpv4First"] = o.ForceIpv4First
	}
	if !IsNil(o.TrustProxy) {
		toSerialize["trustProxy"] = o.TrustProxy
	}
	if !IsNil(o.Proxy) {
		toSerialize["proxy"] = o.Proxy
	}
	if !IsNil(o.DnsCache) {
		toSerialize["dnsCache"] = o.DnsCache
	}
	return toSerialize, nil
}

type NullableNetworkSettings struct {
	value *NetworkSettings
	isSet bool
}

func (v NullableNetworkSettings) Get() *NetworkSettings {
	return v.value
}

func (v *NullableNetworkSettings) Set(val *NetworkSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkSettings(val *NetworkSettings) *NullableNetworkSettings {
	return &NullableNetworkSettings{value: val, isSet: true}
}

func (v NullableNetworkSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


