/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the SettingsMetadatasTestPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SettingsMetadatasTestPostRequest{}

// SettingsMetadatasTestPostRequest struct for SettingsMetadatasTestPostRequest
type SettingsMetadatasTestPostRequest struct {
	Tmdb *bool `json:"tmdb,omitempty"`
	Tvdb *bool `json:"tvdb,omitempty"`
}

// NewSettingsMetadatasTestPostRequest instantiates a new SettingsMetadatasTestPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSettingsMetadatasTestPostRequest() *SettingsMetadatasTestPostRequest {
	this := SettingsMetadatasTestPostRequest{}
	return &this
}

// NewSettingsMetadatasTestPostRequestWithDefaults instantiates a new SettingsMetadatasTestPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSettingsMetadatasTestPostRequestWithDefaults() *SettingsMetadatasTestPostRequest {
	this := SettingsMetadatasTestPostRequest{}
	return &this
}

// GetTmdb returns the Tmdb field value if set, zero value otherwise.
func (o *SettingsMetadatasTestPostRequest) GetTmdb() bool {
	if o == nil || IsNil(o.Tmdb) {
		var ret bool
		return ret
	}
	return *o.Tmdb
}

// GetTmdbOk returns a tuple with the Tmdb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsMetadatasTestPostRequest) GetTmdbOk() (*bool, bool) {
	if o == nil || IsNil(o.Tmdb) {
		return nil, false
	}
	return o.Tmdb, true
}

// HasTmdb returns a boolean if a field has been set.
func (o *SettingsMetadatasTestPostRequest) HasTmdb() bool {
	if o != nil && !IsNil(o.Tmdb) {
		return true
	}

	return false
}

// SetTmdb gets a reference to the given bool and assigns it to the Tmdb field.
func (o *SettingsMetadatasTestPostRequest) SetTmdb(v bool) {
	o.Tmdb = &v
}

// GetTvdb returns the Tvdb field value if set, zero value otherwise.
func (o *SettingsMetadatasTestPostRequest) GetTvdb() bool {
	if o == nil || IsNil(o.Tvdb) {
		var ret bool
		return ret
	}
	return *o.Tvdb
}

// GetTvdbOk returns a tuple with the Tvdb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsMetadatasTestPostRequest) GetTvdbOk() (*bool, bool) {
	if o == nil || IsNil(o.Tvdb) {
		return nil, false
	}
	return o.Tvdb, true
}

// HasTvdb returns a boolean if a field has been set.
func (o *SettingsMetadatasTestPostRequest) HasTvdb() bool {
	if o != nil && !IsNil(o.Tvdb) {
		return true
	}

	return false
}

// SetTvdb gets a reference to the given bool and assigns it to the Tvdb field.
func (o *SettingsMetadatasTestPostRequest) SetTvdb(v bool) {
	o.Tvdb = &v
}

func (o SettingsMetadatasTestPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SettingsMetadatasTestPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Tmdb) {
		toSerialize["tmdb"] = o.Tmdb
	}
	if !IsNil(o.Tvdb) {
		toSerialize["tvdb"] = o.Tvdb
	}
	return toSerialize, nil
}

type NullableSettingsMetadatasTestPostRequest struct {
	value *SettingsMetadatasTestPostRequest
	isSet bool
}

func (v NullableSettingsMetadatasTestPostRequest) Get() *SettingsMetadatasTestPostRequest {
	return v.value
}

func (v *NullableSettingsMetadatasTestPostRequest) Set(val *SettingsMetadatasTestPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSettingsMetadatasTestPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSettingsMetadatasTestPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSettingsMetadatasTestPostRequest(val *SettingsMetadatasTestPostRequest) *NullableSettingsMetadatasTestPostRequest {
	return &NullableSettingsMetadatasTestPostRequest{value: val, isSet: true}
}

func (v NullableSettingsMetadatasTestPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSettingsMetadatasTestPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


