/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the BlocklistGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlocklistGet200Response{}

// BlocklistGet200Response struct for BlocklistGet200Response
type BlocklistGet200Response struct {
	PageInfo *PageInfo `json:"pageInfo,omitempty"`
	Results []BlocklistGet200ResponseResultsInner `json:"results,omitempty"`
}

// NewBlocklistGet200Response instantiates a new BlocklistGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlocklistGet200Response() *BlocklistGet200Response {
	this := BlocklistGet200Response{}
	return &this
}

// NewBlocklistGet200ResponseWithDefaults instantiates a new BlocklistGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlocklistGet200ResponseWithDefaults() *BlocklistGet200Response {
	this := BlocklistGet200Response{}
	return &this
}

// GetPageInfo returns the PageInfo field value if set, zero value otherwise.
func (o *BlocklistGet200Response) GetPageInfo() PageInfo {
	if o == nil || IsNil(o.PageInfo) {
		var ret PageInfo
		return ret
	}
	return *o.PageInfo
}

// GetPageInfoOk returns a tuple with the PageInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlocklistGet200Response) GetPageInfoOk() (*PageInfo, bool) {
	if o == nil || IsNil(o.PageInfo) {
		return nil, false
	}
	return o.PageInfo, true
}

// HasPageInfo returns a boolean if a field has been set.
func (o *BlocklistGet200Response) HasPageInfo() bool {
	if o != nil && !IsNil(o.PageInfo) {
		return true
	}

	return false
}

// SetPageInfo gets a reference to the given PageInfo and assigns it to the PageInfo field.
func (o *BlocklistGet200Response) SetPageInfo(v PageInfo) {
	o.PageInfo = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *BlocklistGet200Response) GetResults() []BlocklistGet200ResponseResultsInner {
	if o == nil || IsNil(o.Results) {
		var ret []BlocklistGet200ResponseResultsInner
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlocklistGet200Response) GetResultsOk() ([]BlocklistGet200ResponseResultsInner, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *BlocklistGet200Response) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []BlocklistGet200ResponseResultsInner and assigns it to the Results field.
func (o *BlocklistGet200Response) SetResults(v []BlocklistGet200ResponseResultsInner) {
	o.Results = v
}

func (o BlocklistGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlocklistGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PageInfo) {
		toSerialize["pageInfo"] = o.PageInfo
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullableBlocklistGet200Response struct {
	value *BlocklistGet200Response
	isSet bool
}

func (v NullableBlocklistGet200Response) Get() *BlocklistGet200Response {
	return v.value
}

func (v *NullableBlocklistGet200Response) Set(val *BlocklistGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableBlocklistGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableBlocklistGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlocklistGet200Response(val *BlocklistGet200Response) *NullableBlocklistGet200Response {
	return &NullableBlocklistGet200Response{value: val, isSet: true}
}

func (v NullableBlocklistGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlocklistGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


