/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the MetadataSettingsSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetadataSettingsSettings{}

// MetadataSettingsSettings struct for MetadataSettingsSettings
type MetadataSettingsSettings struct {
	Tv *string `json:"tv,omitempty"`
	Anime *string `json:"anime,omitempty"`
}

// NewMetadataSettingsSettings instantiates a new MetadataSettingsSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetadataSettingsSettings() *MetadataSettingsSettings {
	this := MetadataSettingsSettings{}
	return &this
}

// NewMetadataSettingsSettingsWithDefaults instantiates a new MetadataSettingsSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetadataSettingsSettingsWithDefaults() *MetadataSettingsSettings {
	this := MetadataSettingsSettings{}
	return &this
}

// GetTv returns the Tv field value if set, zero value otherwise.
func (o *MetadataSettingsSettings) GetTv() string {
	if o == nil || IsNil(o.Tv) {
		var ret string
		return ret
	}
	return *o.Tv
}

// GetTvOk returns a tuple with the Tv field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetadataSettingsSettings) GetTvOk() (*string, bool) {
	if o == nil || IsNil(o.Tv) {
		return nil, false
	}
	return o.Tv, true
}

// HasTv returns a boolean if a field has been set.
func (o *MetadataSettingsSettings) HasTv() bool {
	if o != nil && !IsNil(o.Tv) {
		return true
	}

	return false
}

// SetTv gets a reference to the given string and assigns it to the Tv field.
func (o *MetadataSettingsSettings) SetTv(v string) {
	o.Tv = &v
}

// GetAnime returns the Anime field value if set, zero value otherwise.
func (o *MetadataSettingsSettings) GetAnime() string {
	if o == nil || IsNil(o.Anime) {
		var ret string
		return ret
	}
	return *o.Anime
}

// GetAnimeOk returns a tuple with the Anime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetadataSettingsSettings) GetAnimeOk() (*string, bool) {
	if o == nil || IsNil(o.Anime) {
		return nil, false
	}
	return o.Anime, true
}

// HasAnime returns a boolean if a field has been set.
func (o *MetadataSettingsSettings) HasAnime() bool {
	if o != nil && !IsNil(o.Anime) {
		return true
	}

	return false
}

// SetAnime gets a reference to the given string and assigns it to the Anime field.
func (o *MetadataSettingsSettings) SetAnime(v string) {
	o.Anime = &v
}

func (o MetadataSettingsSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetadataSettingsSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Tv) {
		toSerialize["tv"] = o.Tv
	}
	if !IsNil(o.Anime) {
		toSerialize["anime"] = o.Anime
	}
	return toSerialize, nil
}

type NullableMetadataSettingsSettings struct {
	value *MetadataSettingsSettings
	isSet bool
}

func (v NullableMetadataSettingsSettings) Get() *MetadataSettingsSettings {
	return v.value
}

func (v *NullableMetadataSettingsSettings) Set(val *MetadataSettingsSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableMetadataSettingsSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableMetadataSettingsSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetadataSettingsSettings(val *MetadataSettingsSettings) *NullableMetadataSettingsSettings {
	return &NullableMetadataSettingsSettings{value: val, isSet: true}
}

func (v NullableMetadataSettingsSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetadataSettingsSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


