/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the Blocklist type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Blocklist{}

// Blocklist struct for Blocklist
type Blocklist struct {
	TmdbId *float32 `json:"tmdbId,omitempty"`
	Title *string `json:"title,omitempty"`
	Media *MediaInfo `json:"media,omitempty"`
	UserId *float32 `json:"userId,omitempty"`
}

// NewBlocklist instantiates a new Blocklist object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlocklist() *Blocklist {
	this := Blocklist{}
	return &this
}

// NewBlocklistWithDefaults instantiates a new Blocklist object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlocklistWithDefaults() *Blocklist {
	this := Blocklist{}
	return &this
}

// GetTmdbId returns the TmdbId field value if set, zero value otherwise.
func (o *Blocklist) GetTmdbId() float32 {
	if o == nil || IsNil(o.TmdbId) {
		var ret float32
		return ret
	}
	return *o.TmdbId
}

// GetTmdbIdOk returns a tuple with the TmdbId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Blocklist) GetTmdbIdOk() (*float32, bool) {
	if o == nil || IsNil(o.TmdbId) {
		return nil, false
	}
	return o.TmdbId, true
}

// HasTmdbId returns a boolean if a field has been set.
func (o *Blocklist) HasTmdbId() bool {
	if o != nil && !IsNil(o.TmdbId) {
		return true
	}

	return false
}

// SetTmdbId gets a reference to the given float32 and assigns it to the TmdbId field.
func (o *Blocklist) SetTmdbId(v float32) {
	o.TmdbId = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *Blocklist) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Blocklist) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *Blocklist) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *Blocklist) SetTitle(v string) {
	o.Title = &v
}

// GetMedia returns the Media field value if set, zero value otherwise.
func (o *Blocklist) GetMedia() MediaInfo {
	if o == nil || IsNil(o.Media) {
		var ret MediaInfo
		return ret
	}
	return *o.Media
}

// GetMediaOk returns a tuple with the Media field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Blocklist) GetMediaOk() (*MediaInfo, bool) {
	if o == nil || IsNil(o.Media) {
		return nil, false
	}
	return o.Media, true
}

// HasMedia returns a boolean if a field has been set.
func (o *Blocklist) HasMedia() bool {
	if o != nil && !IsNil(o.Media) {
		return true
	}

	return false
}

// SetMedia gets a reference to the given MediaInfo and assigns it to the Media field.
func (o *Blocklist) SetMedia(v MediaInfo) {
	o.Media = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *Blocklist) GetUserId() float32 {
	if o == nil || IsNil(o.UserId) {
		var ret float32
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Blocklist) GetUserIdOk() (*float32, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *Blocklist) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given float32 and assigns it to the UserId field.
func (o *Blocklist) SetUserId(v float32) {
	o.UserId = &v
}

func (o Blocklist) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Blocklist) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TmdbId) {
		toSerialize["tmdbId"] = o.TmdbId
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Media) {
		toSerialize["media"] = o.Media
	}
	if !IsNil(o.UserId) {
		toSerialize["userId"] = o.UserId
	}
	return toSerialize, nil
}

type NullableBlocklist struct {
	value *Blocklist
	isSet bool
}

func (v NullableBlocklist) Get() *Blocklist {
	return v.value
}

func (v *NullableBlocklist) Set(val *Blocklist) {
	v.value = val
	v.isSet = true
}

func (v NullableBlocklist) IsSet() bool {
	return v.isSet
}

func (v *NullableBlocklist) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlocklist(val *Blocklist) *NullableBlocklist {
	return &NullableBlocklist{value: val, isSet: true}
}

func (v NullableBlocklist) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlocklist) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


