/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses{}

// SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses struct for SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses
type SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses struct {
	Ipv4 *float32 `json:"ipv4,omitempty"`
	Ipv6 *float32 `json:"ipv6,omitempty"`
}

// NewSettingsCacheGet200ResponseDnsCacheEntriesValueAddresses instantiates a new SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSettingsCacheGet200ResponseDnsCacheEntriesValueAddresses() *SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses {
	this := SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses{}
	return &this
}

// NewSettingsCacheGet200ResponseDnsCacheEntriesValueAddressesWithDefaults instantiates a new SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSettingsCacheGet200ResponseDnsCacheEntriesValueAddressesWithDefaults() *SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses {
	this := SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses{}
	return &this
}

// GetIpv4 returns the Ipv4 field value if set, zero value otherwise.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses) GetIpv4() float32 {
	if o == nil || IsNil(o.Ipv4) {
		var ret float32
		return ret
	}
	return *o.Ipv4
}

// GetIpv4Ok returns a tuple with the Ipv4 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses) GetIpv4Ok() (*float32, bool) {
	if o == nil || IsNil(o.Ipv4) {
		return nil, false
	}
	return o.Ipv4, true
}

// HasIpv4 returns a boolean if a field has been set.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses) HasIpv4() bool {
	if o != nil && !IsNil(o.Ipv4) {
		return true
	}

	return false
}

// SetIpv4 gets a reference to the given float32 and assigns it to the Ipv4 field.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses) SetIpv4(v float32) {
	o.Ipv4 = &v
}

// GetIpv6 returns the Ipv6 field value if set, zero value otherwise.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses) GetIpv6() float32 {
	if o == nil || IsNil(o.Ipv6) {
		var ret float32
		return ret
	}
	return *o.Ipv6
}

// GetIpv6Ok returns a tuple with the Ipv6 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses) GetIpv6Ok() (*float32, bool) {
	if o == nil || IsNil(o.Ipv6) {
		return nil, false
	}
	return o.Ipv6, true
}

// HasIpv6 returns a boolean if a field has been set.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses) HasIpv6() bool {
	if o != nil && !IsNil(o.Ipv6) {
		return true
	}

	return false
}

// SetIpv6 gets a reference to the given float32 and assigns it to the Ipv6 field.
func (o *SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses) SetIpv6(v float32) {
	o.Ipv6 = &v
}

func (o SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ipv4) {
		toSerialize["ipv4"] = o.Ipv4
	}
	if !IsNil(o.Ipv6) {
		toSerialize["ipv6"] = o.Ipv6
	}
	return toSerialize, nil
}

type NullableSettingsCacheGet200ResponseDnsCacheEntriesValueAddresses struct {
	value *SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses
	isSet bool
}

func (v NullableSettingsCacheGet200ResponseDnsCacheEntriesValueAddresses) Get() *SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses {
	return v.value
}

func (v *NullableSettingsCacheGet200ResponseDnsCacheEntriesValueAddresses) Set(val *SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses) {
	v.value = val
	v.isSet = true
}

func (v NullableSettingsCacheGet200ResponseDnsCacheEntriesValueAddresses) IsSet() bool {
	return v.isSet
}

func (v *NullableSettingsCacheGet200ResponseDnsCacheEntriesValueAddresses) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSettingsCacheGet200ResponseDnsCacheEntriesValueAddresses(val *SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses) *NullableSettingsCacheGet200ResponseDnsCacheEntriesValueAddresses {
	return &NullableSettingsCacheGet200ResponseDnsCacheEntriesValueAddresses{value: val, isSet: true}
}

func (v NullableSettingsCacheGet200ResponseDnsCacheEntriesValueAddresses) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSettingsCacheGet200ResponseDnsCacheEntriesValueAddresses) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


