/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the SettingsJellyfinUsersGet200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SettingsJellyfinUsersGet200ResponseInner{}

// SettingsJellyfinUsersGet200ResponseInner struct for SettingsJellyfinUsersGet200ResponseInner
type SettingsJellyfinUsersGet200ResponseInner struct {
	Username *string `json:"username,omitempty"`
	Id *string `json:"id,omitempty"`
	Thumb *string `json:"thumb,omitempty"`
	Email *string `json:"email,omitempty"`
}

// NewSettingsJellyfinUsersGet200ResponseInner instantiates a new SettingsJellyfinUsersGet200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSettingsJellyfinUsersGet200ResponseInner() *SettingsJellyfinUsersGet200ResponseInner {
	this := SettingsJellyfinUsersGet200ResponseInner{}
	return &this
}

// NewSettingsJellyfinUsersGet200ResponseInnerWithDefaults instantiates a new SettingsJellyfinUsersGet200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSettingsJellyfinUsersGet200ResponseInnerWithDefaults() *SettingsJellyfinUsersGet200ResponseInner {
	this := SettingsJellyfinUsersGet200ResponseInner{}
	return &this
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *SettingsJellyfinUsersGet200ResponseInner) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsJellyfinUsersGet200ResponseInner) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *SettingsJellyfinUsersGet200ResponseInner) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *SettingsJellyfinUsersGet200ResponseInner) SetUsername(v string) {
	o.Username = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SettingsJellyfinUsersGet200ResponseInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsJellyfinUsersGet200ResponseInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SettingsJellyfinUsersGet200ResponseInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SettingsJellyfinUsersGet200ResponseInner) SetId(v string) {
	o.Id = &v
}

// GetThumb returns the Thumb field value if set, zero value otherwise.
func (o *SettingsJellyfinUsersGet200ResponseInner) GetThumb() string {
	if o == nil || IsNil(o.Thumb) {
		var ret string
		return ret
	}
	return *o.Thumb
}

// GetThumbOk returns a tuple with the Thumb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsJellyfinUsersGet200ResponseInner) GetThumbOk() (*string, bool) {
	if o == nil || IsNil(o.Thumb) {
		return nil, false
	}
	return o.Thumb, true
}

// HasThumb returns a boolean if a field has been set.
func (o *SettingsJellyfinUsersGet200ResponseInner) HasThumb() bool {
	if o != nil && !IsNil(o.Thumb) {
		return true
	}

	return false
}

// SetThumb gets a reference to the given string and assigns it to the Thumb field.
func (o *SettingsJellyfinUsersGet200ResponseInner) SetThumb(v string) {
	o.Thumb = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *SettingsJellyfinUsersGet200ResponseInner) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsJellyfinUsersGet200ResponseInner) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *SettingsJellyfinUsersGet200ResponseInner) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *SettingsJellyfinUsersGet200ResponseInner) SetEmail(v string) {
	o.Email = &v
}

func (o SettingsJellyfinUsersGet200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SettingsJellyfinUsersGet200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Thumb) {
		toSerialize["thumb"] = o.Thumb
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	return toSerialize, nil
}

type NullableSettingsJellyfinUsersGet200ResponseInner struct {
	value *SettingsJellyfinUsersGet200ResponseInner
	isSet bool
}

func (v NullableSettingsJellyfinUsersGet200ResponseInner) Get() *SettingsJellyfinUsersGet200ResponseInner {
	return v.value
}

func (v *NullableSettingsJellyfinUsersGet200ResponseInner) Set(val *SettingsJellyfinUsersGet200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSettingsJellyfinUsersGet200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSettingsJellyfinUsersGet200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSettingsJellyfinUsersGet200ResponseInner(val *SettingsJellyfinUsersGet200ResponseInner) *NullableSettingsJellyfinUsersGet200ResponseInner {
	return &NullableSettingsJellyfinUsersGet200ResponseInner{value: val, isSet: true}
}

func (v NullableSettingsJellyfinUsersGet200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSettingsJellyfinUsersGet200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


