/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the MetadataSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetadataSettings{}

// MetadataSettings struct for MetadataSettings
type MetadataSettings struct {
	Settings *MetadataSettingsSettings `json:"settings,omitempty"`
}

// NewMetadataSettings instantiates a new MetadataSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetadataSettings() *MetadataSettings {
	this := MetadataSettings{}
	return &this
}

// NewMetadataSettingsWithDefaults instantiates a new MetadataSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetadataSettingsWithDefaults() *MetadataSettings {
	this := MetadataSettings{}
	return &this
}

// GetSettings returns the Settings field value if set, zero value otherwise.
func (o *MetadataSettings) GetSettings() MetadataSettingsSettings {
	if o == nil || IsNil(o.Settings) {
		var ret MetadataSettingsSettings
		return ret
	}
	return *o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetadataSettings) GetSettingsOk() (*MetadataSettingsSettings, bool) {
	if o == nil || IsNil(o.Settings) {
		return nil, false
	}
	return o.Settings, true
}

// HasSettings returns a boolean if a field has been set.
func (o *MetadataSettings) HasSettings() bool {
	if o != nil && !IsNil(o.Settings) {
		return true
	}

	return false
}

// SetSettings gets a reference to the given MetadataSettingsSettings and assigns it to the Settings field.
func (o *MetadataSettings) SetSettings(v MetadataSettingsSettings) {
	o.Settings = &v
}

func (o MetadataSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetadataSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Settings) {
		toSerialize["settings"] = o.Settings
	}
	return toSerialize, nil
}

type NullableMetadataSettings struct {
	value *MetadataSettings
	isSet bool
}

func (v NullableMetadataSettings) Get() *MetadataSettings {
	return v.value
}

func (v *NullableMetadataSettings) Set(val *MetadataSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableMetadataSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableMetadataSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetadataSettings(val *MetadataSettings) *NullableMetadataSettings {
	return &NullableMetadataSettings{value: val, isSet: true}
}

func (v NullableMetadataSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetadataSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


