/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the OverrideRule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OverrideRule{}

// OverrideRule struct for OverrideRule
type OverrideRule struct {
	Id *string `json:"id,omitempty"`
}

// NewOverrideRule instantiates a new OverrideRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOverrideRule() *OverrideRule {
	this := OverrideRule{}
	return &this
}

// NewOverrideRuleWithDefaults instantiates a new OverrideRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOverrideRuleWithDefaults() *OverrideRule {
	this := OverrideRule{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *OverrideRule) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OverrideRule) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *OverrideRule) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *OverrideRule) SetId(v string) {
	o.Id = &v
}

func (o OverrideRule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OverrideRule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableOverrideRule struct {
	value *OverrideRule
	isSet bool
}

func (v NullableOverrideRule) Get() *OverrideRule {
	return v.value
}

func (v *NullableOverrideRule) Set(val *OverrideRule) {
	v.value = val
	v.isSet = true
}

func (v NullableOverrideRule) IsSet() bool {
	return v.isSet
}

func (v *NullableOverrideRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOverrideRule(val *OverrideRule) *NullableOverrideRule {
	return &NullableOverrideRule{value: val, isSet: true}
}

func (v NullableOverrideRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOverrideRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


